### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by erikvdvelden** [aws/aws-sdk-android#103]
Sometimes my application crashes with this exception:

FATAL EXCEPTION: main
                                                                          java.util.ConcurrentModificationException
                                                                              at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
                                                                              at com.amazonaws.mobileconnectors.s3.transferutility.TransferStatusUpdater$3.run(TransferStatusUpdater.java:248)
                                                                              at android.os.Handler.handleCallback(Handler.java:730)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                              at android.os.Looper.loop(Looper.java:137)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5136)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:525)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:760)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
                                                                              at dalvik.system.NativeStart.main(Native Method)

Probably this is due to the fact that in the onError I call both 
        observer.cleanTransferListener();
        transferUtility.deleteTransferRecord(observer.getId());

**Comment by fosterzhang** [comment]
Thanks for reporting, I'll look into this.

**Comment by fosterzhang** [comment]
This is fixed in v2.2.13 release. Please update the SDK at https://aws.amazon.com/mobile/sdk/. Check out what is changed in the [change log](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md).

**Comment by erikvdvelden** [comment]
Wow. I did not expect such a fast turn around time on my issues! Great work. Thanks.
