### ISSUE TITLE
AWS-Mobile Analytics

### ISSUE THREAD

**Issue by bdipak** [aws/aws-sdk-android#110]
EventStoreException while getSessionClient().pauseSession() leading to app crash.
SDK: 'com.amazonaws:aws-android-sdk-mobileanalytics:2.2.12'

java.lang.RuntimeException: Unable to pause activity {XXXActivity}: com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.delivery.EventStoreException: Unable to open session file writer
    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2906)
    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2862)
    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2840)
    at android.app.ActivityThread.access$900(ActivityThread.java:143)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1258)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4960)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.delivery.EventStoreException: Unable to open session file writer
    at com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.session.FileSessionStore.tryInitializeWriter(FileSessionStore.java:100)
    at com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.session.FileSessionStore.storeSession(FileSessionStore.java:70)
    at com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.session.client.SessionClientState.executePause(SessionClientState.java:107)
    at com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.session.client.ActiveSessionState.pause(ActiveSessionState.java:48)
    at com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.session.client.DefaultSessionClient.pauseSession(DefaultSessionClient.java:92)

Caused by: java.io.FileNotFoundException: /XXX/app_119f9c4fe2a347158f8eb5694564f123515d6767-01b7-49e5-8273-c8d11b0f331d/sessions/sessionFile: open failed: ENOENT (No such file or directory)
    at libcore.io.IoBridge.open(IoBridge.java:416)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
    at com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.core.system.DefaultFileManager.newOutputStream(DefaultFileManager.java:123)
    at com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.session.FileSessionStore.tryInitializeWriter(FileSessionStore.java:96)
    ... 21 more
Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
    at libcore.io.Posix.open(Native Method)
    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
    at libcore.io.IoBridge.open(IoBridge.java:400)

**Comment by fosterzhang** [comment]
Does the problem happen consistently? How to reproduce it?

**Comment by bdipak** [comment]
It is reported only once. And our app user has reported it via playstore.
So I am not aware of any specific steps to reproduce it.

**Comment by fosterzhang** [comment]
@bdipak it's hard to diagnose without a reliable way to reproduce it. The stacktrace says the file that stores session data is not found. Not sure where you store the file. It could be that the file is removed by customer via clear app data in system settings.

**Comment by bdipak** [comment]
@fosterzhang I guess the file gets stored in the default location which aws mobile analytics sdk specifies.  Not sure if clearing app data will clear that file. But in either case, shouldn't aws sdk consume this error ? It would be pain if every application which uses aws mobile analytics needs to explicitly handle exceptions related to analytics error. What do you think ?

**Comment by fosterzhang** [comment]
The session file is saved under the application. It'll be erased if the app data is cleared by user, which is rare. Anyway, I agree that it should be handled by the SDK.

**Comment by richabra** [comment]
I was not able to replicate this issue, but from my research it looks like it should happen if the user had removed expected directories. I've added code to ensure these directories are around, otherwise I return a session store exception back up. Now if a session store exception occurs it means there is a real issue saving the session and needs to be handled otherwise events will be lost. I am marking this issue as fixed, please update to at least version 2.3.6 of the SDK. Thank you.
