### ISSUE TITLE
Fatal Exception: isNetworkConnected on a null object reference

### ISSUE THREAD

**Issue by virengujariya** [aws/aws-sdk-android#121]
I'm getting following error when using aws-android-sdk-s3 ```Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.amazonaws.mobileconnectors.s3.transferutility.TransferService$NetworkInfoReceiver.isNetworkConnected()' on a null object reference
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferService.execCommand(TransferService.java:287)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferService$UpdateHandler.handleMessage(TransferService.java:224)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)```

**Comment by fosterzhang** [comment]
Which version are you using? This is a known bug in v2.2.14 and should be fixed in v2.2.15.

**Comment by virengujariya** [comment]
I'm using v2.2.14. Will upgrade to v2.2.15
