### ISSUE TITLE
AmazonS3Client.putObject takes a long time to time out when connection is being toggled

### ISSUE THREAD

**Issue by miketrewartha** [aws/aws-sdk-android#125]
We're trying to "stress" test our app's ability to upload some picture files (~5MB a piece). We've made use of some throttling functionality in Charles Proxy and then set the emulator to toggle wifi on for 15 secs, then off for 5 secs. All of the throttling and toggling appears to be working as intended. Now, if we kick off an upload via an `AmazonS3Client`'s `putObject` method, things usually work great and it's quite resilient. That said, we have our own retry logic we'd like to implement and so, when creating out `AmazonS3Client`, we set the following `ClientConfiguration`:

```java
ClientConfiguration clientConfiguration = new ClientConfiguration()
        .withMaxErrorRetry(MAX_ERROR_RETRY) // 0 retries
        .withConnectionTimeout(CONNECTION_TIMEOUT_IN_MS) // 30,000 ms
        .withSocketTimeout(SOCKET_TIMEOUT_IN_MS); // 30,000 ms
amazonS3 = new AmazonS3Client(credentialsProvider, clientConfiguration);
```

When we call `putObject` during these crazy connection states, it just seems to take way longer than the 30 secs we've specified in order to time out. Are we misunderstanding something or doing something wrong here? Any help would be appreciated! Here's a snippet from a thread dump that shows the code's just waiting somewhere in okio for a write to finish... If this looks like an issue with okio, I'll definitely post there, but I wanted to make sure the `ClientConfiguration` stuff we're doing is correct first. Thanks folks!

```java
java.lang.Thread.State: RUNNABLE
	  at com.android.org.conscrypt.NativeCrypto.SSL_write(NativeCrypto.java:-1)
	  at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:771)
	  - locked <0x1f17> (a java.lang.Object)
	  at com.android.okhttp.okio.Okio$1.write(Okio.java:76)
	  at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
	  at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
	  at com.android.okhttp.okio.RealBufferedSink.write(RealBufferedSink.java:46)
	  at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:302)
	  at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
	  at com.android.okhttp.okio.RealBufferedSink$1.write(RealBufferedSink.java:198)
	  at com.amazonaws.http.UrlHttpClient.write(UrlHttpClient.java:172)
	  at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:129)
	  at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
	  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:360)
	  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
	  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221)
	  at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1628)
	  at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1443)
```

**Comment by fosterzhang** [comment]
@miketrewartha Your socket timeout is set to 30 seconds. It means the client will wait up to 30 seconds before receiving some data over the wire. It's not accumulative. If you toggle network on and off every 5-15 seconds, it isn't long enough to trigger socket timeout exception.

**Comment by miketrewartha** [comment]
Thanks @fosterzhang, that's kind of what I was hoping to hear. Appreciate the quick reply!

**Comment by bernieatenovlab** [comment]
Was the solution to increase or decrease the timeout?

**Comment by miketrewartha** [comment]
@bernieatenovlab Sorry for the late response. We decreased both timeouts, setting the connection timout to 5 secs and the socket timeout to 10 secs. The important thing there was that both are lower than the wifi toggling interval we had, so the timeout exceptions got triggered.

**Comment by kkkabariya** [comment]
hello....
 i just first time register in my app using AmazonDynamoDBClient in android
 after delete account does not delete how to do this ?

but after register ont time logout and login process complete after delete account that is success how ?

**Comment by kvasukib** [comment]
@kkkabariya Sorry for the inconvenience caused. Can you open a new issue with the adequate information?
