### ISSUE TITLE
Crash while creating the base directory

### ISSUE THREAD

**Issue by ukpa** [aws/aws-sdk-android#126]
`05-08 01:01:33.724 21196-22334/com.angleapp E/AndroidRuntime: FATAL EXCEPTION: Thread-949
                                                              Process: com.angleapp, PID: 21196
                                                              java.lang.RuntimeException: Can't create directory the base directory ('/data/user/0/com.angleapp/files/s3_angleapp-userfiles-mobilehub-1491286053/public') for storing local content.
                                                                  at com.amazonaws.mobile.content.ContentManager.<init>(ContentManager.java:229)
                                                                  at com.amazonaws.mobile.content.UserFileManager.<init>(UserFileManager.java:0)
                                                                  at com.amazonaws.mobile.content.UserFileManager$Builder$1.run(UserFileManager.java:131)
                                                                  at java.lang.Thread.run(Thread.java:818)`

As soon as the app authenticates the user, it crashes throwing the above error. But somehow it works fine after reopening it.

**Comment by achud** [comment]
Hi, ukpa.

Sorry to hear you're having problems with the User Data Storage feature in Mobile Hub. Can you please provide some information:
1. What type of device or emulator were you using?
2. Which Android operating system version were you using?
3. Did you have this problem in the downloaded quickstart app or only after you copied/pasted the code to your own app project?
4. In your own app project, did you create more than one instance of the UserFileManager or ContentManager? If so, did you attempt to point them at the same S3 bucket?

Once we have the info above, we should be able to help point you in the right direction.

thanks,
Andrew C
AWS Mobile Applications

**Comment by wdane** [comment]
Assuming issue is resolved. Please re-open if you are still having issues.
