### ISSUE TITLE
User Pool Lambda Trigger

### ISSUE THREAD

**Issue by adelpuva** [aws/aws-sdk-android#139]
I create a Lamba and I use it for User Pool "Pre sign-up" Trigger, this is the simple code:

```
exports.handler = function(event, context) {
    event.response.autoConfirmUser = true;
    context.done(null, event);
}
```

When I call _CognitoUserPool.signUpInBackground()_ the user is created (and confirmed without mail is sent) but before _SignUpHandler_ is called  Android SDK launches this exception:

```
E/AndroidRuntime: FATAL EXCEPTION: mai java.lang.NullPointerException at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserCodeDeliveryDetails.<init>(CognitoUserCodeDeliveryDetails.java:50) 
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUserPool$1$1.run(CognitoUserPool.java:199) 
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:5419)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
at dalvik.system.NativeStart.main(Native Method)
```
If I remove Trigger from User Pool (without change my Android code) the signUp works fine without any exception.

Why this error?

**Comment by behrooziAWS** [comment]
This issue should be resolved in 2.2.17: https://github.com/aws/aws-sdk-android/commit/c36e6f6937d16a661087d8c3e879b43cbfc8097f#diff-1cf6f8dfe10f4f1eff8e806242a3c01d
