### ISSUE TITLE
SSLException during upload file in the bucket in aws-sdk 2.2.17

### ISSUE THREAD

**Issue by jinguoliang** [aws/aws-sdk-android#147]
Hello, I use VPN of H.K. in china. The bucket is us-east-1. The issues below are often occurs.

The issue happen on small file (< 5m) more frequently. Often After I upload a large file The small file also upload successfully.

The frequency of issue is not stable。

I hope your help. Or you can give me some light. :)

##Some like this:

AmazonHttpClient: Unable to execute HTTP request: failed to connect to s3.amazonaws.com/54.231.14.240 (port 443) after 15000ms
                                                                  java.net.SocketTimeoutException: failed to connect to s3.amazonaws.com/54.231.14.240 (port 443) after 15000ms
                                                                      at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
                                                                      at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                                                      at java.net.Socket.connect(Socket.java:882)
                                                                      at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
                                                                      at com.android.okhttp.Connection.connect(Connection.java:152)
                                                                      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
                                                                      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
                                                                      at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
                                                                      at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
                                                                      at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:217)
                                                                      at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
                                                                      at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
                                                                      at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:128)
                                                                      at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
                                                                      at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
                                                                      at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
                                                                      at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4204)
                                                                      at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1618)
                                                                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:174)
                                                                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:74)
                                                                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:40)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
05-24 19:52:53.691 24475-18352/com.duapps.rec E/UploadTask: Unable to execute HTTP request: failed to connect to s3.amazonaws.com/54.231.14.240 (port 443) after 15000ms

##Some like this: 

AmazonHttpClient: Unable to execute HTTP request: Read timed out
                                                                  java.net.SocketTimeoutException: Read timed out
                                                                      at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
                                                                      at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
                                                                      at com.android.okio.Okio$2.read(Okio.java:113)
                                                                      at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:147)
                                                                      at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:94)
                                                                      at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
                                                                      at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
                                                                      at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
                                                                      at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
                                                                      at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
                                                                      at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:496)
                                                                      at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
                                                                      at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:25)
                                                                      at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:72)
                                                                      at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:66)
                                                                      at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
                                                                      at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
                                                                      at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4204)
                                                                      at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1618)
                                                                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:174)
                                                                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:74)
                                                                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:40)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
05-24 20:18:36.810 24475-24497/com.duapps.rec E/UploadTask: Unable to execute HTTP request: Read timed out

##Some like this:

AmazonHttpClient: Unable to execute HTTP request: Write error: ssl=0xae839200: I/O error during system call, Connection reset by peer
                                                                  javax.net.ssl.SSLException: Write error: ssl=0xae839200: I/O error during system call, Connection reset by peer
                                                                      at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
                                                                      at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:765)
                                                                      at com.android.okio.Okio$1.write(Okio.java:70)
                                                                      at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
                                                                      at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
                                                                      at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:291)
                                                                      at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
                                                                      at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
                                                                      at com.amazonaws.http.UrlHttpClient.write(UrlHttpClient.java:172)
                                                                      at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:129)
                                                                      at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
                                                                      at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
                                                                      at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
                                                                      at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4204)
                                                                      at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1618)
                                                                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:174)
                                                                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:74)
                                                                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:40)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:818)
05-24 20:55:46.716 26236-30985/com.duapps.rec E/UploadTask: Unable to execute HTTP request: Write error: ssl=0xae839200: I/O error during system call, Connection reset by peer

**Comment by fosterzhang** [comment]
@jinguoliang The timeout issue can be solved by increasing both socket timeout and connection timeout via [ClientConfiguration](http://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html). There is no good solution to "Connection reset by peer". You need a better network.

**Comment by anilshar** [comment]
Hi, 

Upload is failing due to timeout issues. This is a very frequent issue in my case. I am also on a reasonably good internet connection. 

I am also facing a lot of related to issues and I have also tried to change the socket & connection timeout to 250 second from default 15 second. 


Stack trace

                                                                            com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
                                                                                at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:428)
                                                                                at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
                                                                                at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221)
                                                                                at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1628)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:205)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:86)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:45)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)
                                                                             Caused by: java.net.SocketTimeoutException: timeout
                                                                                at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:207)
                                                                                at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
                                                                                at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                                                at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                                                                at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                                                                at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                                                                at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
                                                                                at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                                                                                at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:904)
                                                                                at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
                                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
                                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:497)
                                                                                at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
                                                                                at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java)
                                                                                at com.newrelic.agent.android.instrumentation.HttpsURLConnectionExtension.getResponseMessage(HttpsURLConnectionExtension.java:251)
                                                                                at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:72)
                                                                                at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:66)
                                                                                at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:360)
                                                                                at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
                                                                                at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221)
                                                                                at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1628)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:205)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:86)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:45)
                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                at java.lang.Thread.run(Thread.java:818)

**Comment by anilshar** [comment]
Question/Tip 

Should I upload files sequentially i.e. wait for previous items to upload first and then try for the next item?  

I have designed an upload system where I am calling getTransferUtility().upload() for all the local files to upload in parallel. Basically I am not waiting for first item to compete uploading and then try to upload the next item to be uploaded. 

However the upload is failing for when there is only one item to be uploaded. 
The upload is failing for both photos and videos.

**Comment by anilshar** [comment]
I am using 2.2.16 android sdk for file upload purpose.

**Comment by fosterzhang** [comment]
@anilshar You don't have to wait for the first item to complete.

As for the timeout issue, if increasing timeout doesn't help, you can try the following:
- Choose a region closer to you. Singapore ap-southeast-1 is probably better than IAD us-east-1 if you are in Asia.
- Enable S3 transfer acceleration. See [Amazon S3 Transfer Acceleration](http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html) for more information.
- Check with your ISP.

**Comment by anilshar** [comment]
@fosterzhang 

Thanks for the info. 

I am using US_EAST_1 region for CognitoCachingCredentialsProvider as Amazon Cognito service is not available in Singapore region as of now.  The S3 bucket is in Singapore only. 

As per my knowledge Amazon S3 Transfer Acceleration suits more when you need to transfer large amount of data and internet speed is also faster. 
But, I am trying to build a solution for the app which would be used in villages/tier-2 cities of India, where mobile data Internet is assumed to be poor.  Would it be good idea to try Amazon S3 Transfer Acceleration for my use case?

How can I tune the solution to avoid timeout failure and achieve faster uploads. Please add some pointers. 

I also had couple of question regarding clientConfiguration, please help me to understand it better. 
What would be the optimal values for slow internet connection(2G/3G).  Should I change MaxConnections to an higher value ( around 20) when the user is on good connection(wifi/4G maybe) else set it to 8. 


 ClientConfiguration clientConfiguration = new ClientConfiguration();
            clientConfiguration.setSocketTimeout(300000);  // 5min 
            clientConfiguration.setConnectionTimeout(30000); // 0.5 min
            clientConfiguration.setMaxErrorRetry(3); 
            clientConfiguration.setMaxConnections(8); // what would be an optimal value here.

**Comment by fosterzhang** [comment]
@anilshar Amazon S3 Transfer Acceleration will definitely help. It not only increases transfer speed but also reduces latency.

There are no optimal values. You need to tune them to satisfy your use case. FYI max connection is probably not honored after the SDK switches to HttpUrlConnection.
