### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Unknown URI: content://com.packagename/transfers/-1

### ISSUE THREAD

**Issue by nagendraksrivastava** [aws/aws-sdk-android#170]
at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBBase.query(Unknown)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.queryTransferById(Unknown)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.getTransferById(Unknown)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferService.execCommand(Unknown)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferService$UpdateHandler.handleMessage(Unknown)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)

Multiple vendor device 

Free space 4 GB 
Free RAM 403.11 MB

Please fix the issue it is keep happening

**Comment by fosterzhang** [comment]
@nagendraksrivastava How to reproduce the issue?

**Comment by wdane** [comment]
Assuming resolved, please re-open if you have a way to reproduce this or a pattern of occurrence.
