### ISSUE TITLE
AWS Mobile Analytics: Out of memory error

### ISSUE THREAD

**Issue by bdipak** [aws/aws-sdk-android#178]
Please find the below stack trace. I don't have any particular step to reproduce this.It is reported only once. And our app user has reported it via playstore.
SDK: 'com.amazonaws:aws-android-sdk-mobileanalytics:2.2.12'

I don't think it would be possible to debug this issue with the limited information provided but I feel it would be helpful if aws sdk consume this error.

java.lang.OutOfMemoryError
	at java.lang.String.<init>(String.java:422)
	at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:642)
	at java.lang.StringBuilder.toString(StringBuilder.java:663)
	at org.json.JSONStringer.toString(JSONStringer.java:430)
	at org.json.JSONArray.toString(JSONArray.java:575)
	at com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.delivery.ERSRequestBuilder.createRecordEventsRequest(ERSRequestBuilder.java)
	at com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.delivery.DefaultDeliveryClient.submitEvents(DefaultDeliveryClient.java)
	at com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.delivery.DefaultDeliveryClient$3.run(DefaultDeliveryClient.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

**Comment by wdane** [comment]
It looks like when the events are being read from storage to be sent it is causing the phone to run out of memory. The default max size of events per individual request is relatively small, only 102400 characters (so if they are all ASCII characters, then 102kB). Are you using any options to increase this length? It's possible there is a bug causing a memory leak during submission. Do you know the approximate size of the records you are sometimes sending? Are you sending GB's of events?

**Comment by wdane** [comment]
Closing, feel free to re-open if this is still happening.
