### ISSUE TITLE
java.lang.NullPointerException calling provider.refresh()

### ISSUE THREAD

**Issue by adelpuva** [aws/aws-sdk-android#181]
When I call _provider.refresh()_, sometimes, is thrown this exception:
> java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:465)

My code is:
```
Map<String, String> logins = new HashMap<>();
logins.put(providerName, token);
provider.setLogins(logins);
provider.refresh();
```
This error is happen with **2.2.20**, I upgrade to **2.2.21** only yestarday...

Thank you

**Comment by jbailey2010** [comment]
Can you clarify your last comment? Does that mean it's only happening in 2.2.20 but not 2.2.21?

**Comment by jbailey2010** [comment]
And can you provide a snippet of how you're initializing your credentials provider so we can trace it through the SDK?

**Comment by adelpuva** [comment]
Only with 2.2.20. 

Now I'm using 2.2.22 (No 2.3.0 for this reason: https://github.com/aws/aws-sdk-android/issues/129#issuecomment-240662284), and the problem is not happen yet.

This is my code:

```
    public static void init(final Context context) {
        Resources res = context.getResources();

        regions = Regions.fromName(res.getString(R.string.aws_region));

        ClientConfiguration clientConfiguration = new ClientConfiguration();

        provider = new CognitoCachingCredentialsProvider(
                context,
                res.getString(R.string.aws_identity_pool_id),
                regions,
                clientConfiguration
        );

        syncClient = new CognitoSyncManager(context, regions, provider);

        userPool = new CognitoUserPool(context,
                res.getString(R.string.aws_user_pool_id),
                res.getString(R.string.aws_user_pool_client_id),
                res.getString(R.string.aws_user_pool_client_secret),
                clientConfiguration
        );

        AmazonS3 s3 = new AmazonS3Client(provider);
        s3.setRegion(Region.getRegion(Regions.fromName(res.getString(R.string.aws_bucket_region))));
        
        transferUtility = new TransferUtility(s3, context);

        provider.registerIdentityChangedListener(new IdentityChangedListener() {
            @Override
            public void identityChanged(String oldIdentityId, String newIdentityId) {
                Logs.onlyIfDebug(String.format("[identityChanged] OLD: %s", oldIdentityId));
                Logs.onlyIfDebug(String.format("[identityChanged] NEW: %s", newIdentityId));
            }
        });
    }

    public static void logIn(final Context context, final String providerName, final String token) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    Logs.onlyIfDebug(String.format("[logIn / bck] for %s", providerName));
                    Map<String, String> logins = new HashMap<>();
                    logins.put(providerName, token);
                    provider.setLogins(logins);
                    // FIXME Amazon must fix it!
                    // java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
                    // at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:465)
                    // at com.neosperience.android.user.AWSHelper$3.run(AWSHelper.java:354)
                    provider.refresh();
                    createLambdaFactory(context);
                } catch (Exception e) {
                    AWSHelper.logOut(context);
                }
            }
        }).start();
    }

    public static void logOut(Context context) {
        Logs.onlyIfDebug("logOut");

        if (userPool != null && userPool.getCurrentUser() != null) {
            userPool.getCurrentUser().signOut();
            Logs.onlyIfDebug("logOut -> UserPool -> SignOut");
        }

        if (provider != null) {
            provider.getLogins().clear();
            provider.clear();
            Logs.onlyIfDebug("logOut -> Provider -> Clear");
        }

        if (syncClient != null) {
            syncClient.openOrCreateDataset(Const.DATASET).delete();
            syncClient.wipeData();
            Logs.onlyIfDebug("logOut -> sync -> delete/wipeData");
        }
    }

    private static void createLambdaFactory(Context context) {
        Logs.onlyIfDebug("[createLambdaFactory]");
        ClientConfiguration config = new ClientConfiguration();
        config.setSocketTimeout(1 * 60 * 1000); 
        lambdaInvokerFactory = new LambdaInvokerFactory(context, regions, provider, config);
    }
```

**Comment by jbailey2010** [comment]
Just to test, can you give it a run through with 2.3.0?

Were you running into the issue on every run with 2.2.20, or was it intermittent?

**Comment by adelpuva** [comment]
With 2.2.20 was intermittent, while with 2.2.22 is not happened yet!
(I can test 2.3.0 because my device test is <19 )

**Comment by jbailey2010** [comment]
I have thus far not been able to reproduce with the more recent SDKs, has it been behaving? It may have just been an issue with an older one.

**Comment by wdane** [comment]
Closing for now, please re-open if issue occurs in newer SDK releases.
