### ISSUE TITLE
AWS se video upload fails

### ISSUE THREAD

**Issue by kiranboghra** [aws/aws-sdk-android#186]
whe i try to upload video from nexus 5x device over wifi connection uploading failed with following log,

08-09 12:06:36.693 17837-18769/com.numberatank I/AmazonHttpClient: Unable to execute HTTP request: timeout
                                                                   java.net.SocketTimeoutException: timeout
                                                                       at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
                                                                       at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
                                                                       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
                                                                       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                                                       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                                                       at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                                                       at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
                                                                       at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                                                                       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
                                                                       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782)
                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:517)
                                                                       at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:72)
                                                                       at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:66)
                                                                       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:360)
                                                                       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
                                                                       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221)
                                                                       at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3312)
                                                                       at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:48)
                                                                       at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:28)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                       at java.lang.Thread.run(Thread.java:761)
                                                                    Caused by: java.net.SocketException: Socket closed
                                                                       at java.net.SocketInputStream.socketRead0(Native Method)
                                                                       at java.net.SocketInputStream.read(SocketInputStream.java:151)
                                                                       at java.net.SocketInputStream.read(SocketInputStream.java:120)
                                                                       at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
                                                                       at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                                       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306) 
                                                                       at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300) 
                                                                       at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196) 
                                                                       at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191) 
                                                                       at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80) 
                                                                       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906) 
                                                                       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782) 
                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463) 
                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405) 
                                                                       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:517) 
                                                                       at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:72) 
                                                                       at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:66) 
                                                                       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:360) 
                                                                       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199) 
                                                                       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4221) 
                                                                       at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3312) 
                                                                       at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:48) 
                                                                       at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:28) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                       at java.lang.Thread.run(Thread.java:761)

**Comment by kiranboghra** [comment]
I am using and my wifi connection is quite good, 

 compile 'com.amazonaws:aws-android-sdk-core:2.2.15'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.2.15'
    compile 'com.amazonaws:aws-android-sdk-s3:2.2.15'

I am using TransferUtility,

  public static TransferUtility getTransferUtility(Context context) {
        if (sTransferUtility == null) {
            sTransferUtility = new TransferUtility(getS3Client(context.getApplicationContext()),
                    context.getApplicationContext());
        }
        return sTransferUtility;
    }


  public static AmazonS3Client getS3Client(Context context) {
        if (sS3Client == null) {
            ClientConfiguration clientConfig = new ClientConfiguration();
            clientConfig.setProtocol(Protocol.HTTP);
            BasicAWSCredentials credentials = new BasicAWSCredentials(Constants.AWS_ACCESS_KEY_ID, Constants.AWS_SECRET_ACCESS_KEY);
            sS3Client = new AmazonS3Client(credentials, clientConfig);
            sS3Client.setRegion(Region.getRegion(Regions.AP_SOUTHEAST_1));
        }
        return sS3Client;
    }

**Comment by wdane** [comment]
Hmm a socket timeout usually means that too much time has passed without data getting from the device to the server.

A few questions)
1) Does this only happen on Nexus 5x devices? Have you tried other devices?
2) I see you are using AP_SOUTHEAST_1, where are your requests originating from?
3) Does this happen with HTTPS as well?
4) Have you tried increasing the socket timeout in the ClientConfiguration?

Also for testing/development using BasicAWSCredentials is fine, but when releasing your app, these are very insecure and I would recommend using Amazon Cognito for authenticating your users (https://aws.amazon.com/cognito/).

**Comment by kiranboghra** [comment]
NO this issue is not only happen in nexus 5x but it happens in all the devices including emulators. One more thing java.net.SocketTimeoutException: timeout error occurs after total bytes of file sent to AWS server.  but the issue is TransferState.COMPLETED is not called and instead SocketTimeoutException occurs. I am requesting from Gujarat, India.

As suggested bu you when I increasing the socket timeout in the ClientConfiguration this error is not occurring and working fine. I have increased socket timeout from default value to 60000 milliseconds. So what you think is this bug or should I use increased socket timeout value 60000 milliseconds

TransferState.COMPLETED is called after 20-25 second after total bytes of file sent to AWS  Server. I think this may be a problem because default socket timeout  value is 15 seconds. So when I increase value to 60 second it's working.

**Comment by kiranboghra** [comment]
Sometimes the same error also occurs with 60000 milliseconds in the socket timeout in the ClientConfiguration. So any other suggestion?

**Comment by wdane** [comment]
How many things are you uploading at the same time? For multi-part uploads, which the transfer utility uses for large files, the complete multipart upload request is placed on the thread scheduler after all the parts have completed. If you are uploading many things, I could potentially see it getting starved while other video pieces are uploading. Are you uploading only one video at a time?

**Comment by kiranboghra** [comment]
I am uploading only one video file at a time. and maximum file I am uploading is 20 MB. I am not uploading file more than 20 MB.

**Comment by wdane** [comment]
The only thing that makes sense for this error is that the internet is failing between completing the upload and successfully sending the complete multipart upload request. I'm going to close this issue for now unless you get some new pattern that we can dig into.
