### ISSUE TITLE
TransferUtility + AmazonS3EncryptionClient; has anyone been able to get it to work between different devices?

### ISSUE THREAD

**Issue by hs8058** [aws/aws-sdk-android#229]
Hi,

I may be wrong but I have tried all combinations so far with no luck.

After taking care of https://github.com/aws/aws-sdk-android/issues/214 temporarily, now the issue is that no matter what type of key is used, either symmetric or asymmetric, and no matter how I share the key between two parties, the download/decrypt end always fails when different devices try to upload and download files using TransferUtility and AmazonS3EncryptionClient.

The keys are serialized as strings and transferred through secure channels and later are converted back into keys.

Disturbingly, tests on the same machine succeed with key to string and string to key conversion but the second the string to key conversion happens on another device, I get the following exception:

Any thoughts?

Best,

H.

Exception:

Failed to download: 212 due to Unable to decrypt symmetric key from object metadata : checksum failed
Error during download: 212
                                                   com.amazonaws.AmazonClientException: Unable to decrypt symmetric key from object metadata : checksum failed
                                                       at com.amazonaws.services.s3.internal.crypto.ContentCryptoMaterial.cek(ContentCryptoMaterial.java:205)
                                                       at com.amazonaws.services.s3.internal.crypto.ContentCryptoMaterial.fromObjectMetadata(ContentCryptoMaterial.java:266)
                                                       at com.amazonaws.services.s3.internal.crypto.S3CryptoModuleAE.decipherWithMetadata(S3CryptoModuleAE.java:233)
                                                       at com.amazonaws.services.s3.internal.crypto.S3CryptoModuleAE.decipher(S3CryptoModuleAE.java:172)
                                                       at com.amazonaws.services.s3.internal.crypto.S3CryptoModuleAE.getObjectSecurely(S3CryptoModuleAE.java:153)
                                                       at com.amazonaws.services.s3.internal.crypto.CryptoModuleDispatcher.getObjectSecurely(CryptoModuleDispatcher.java:93)
                                                       at com.amazonaws.services.s3.AmazonS3EncryptionClient.getObject(AmazonS3EncryptionClient.java:417)
                                                       at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:93)
                                                       at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:39)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:841)
                                                    Caused by: java.security.InvalidKeyException: checksum failed
                                                       at com.android.org.bouncycastle.jcajce.provider.symmetric.util.BaseWrapCipher.engineUnwrap(BaseWrapCipher.java:326)
                                                       at javax.crypto.Cipher.unwrap(Cipher.java:1409)
                                                       at com.amazonaws.services.s3.internal.crypto.ContentCryptoMaterial.cek(ContentCryptoMaterial.java:187)
                                                       at com.amazonaws.services.s3.internal.crypto.ContentCryptoMaterial.fromObjectMetadata(ContentCryptoMaterial.java:266) 
                                                       at com.amazonaws.services.s3.internal.crypto.S3CryptoModuleAE.decipherWithMetadata(S3CryptoModuleAE.java:233) 
                                                       at com.amazonaws.services.s3.internal.crypto.S3CryptoModuleAE.decipher(S3CryptoModuleAE.java:172) 
                                                       at com.amazonaws.services.s3.internal.crypto.S3CryptoModuleAE.getObjectSecurely(S3CryptoModuleAE.java:153) 
                                                       at com.amazonaws.services.s3.internal.crypto.CryptoModuleDispatcher.getObjectSecurely(CryptoModuleDispatcher.java:93) 
                                                       at com.amazonaws.services.s3.AmazonS3EncryptionClient.getObject(AmazonS3EncryptionClient.java:417) 
                                                       at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:93) 
                                                       at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:39) 
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                       at java.lang.Thread.run(Thread.java:841)

**Comment by karthiksaligrama** [comment]
Lets continue to track this in #214
