### ISSUE TITLE
Fatal Exception: com.amazonaws.AmazonClientException

### ISSUE THREAD

**Issue by alirezaafkar** [aws/aws-sdk-android#231]
`
Fatal Exception: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.us-east-1.amazonaws.com": No address associated with hostname
       at com.amazonaws.http.AmazonHttpClient.executeHelper(Unknown Source:424)
       at com.amazonaws.http.AmazonHttpClient.execute(Unknown Source:199)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(Unknown Source:558)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(Unknown Source:388)
       at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(Unknown Source:1651)
       at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(Unknown Source:371)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(Unknown Source:441)
       at com.amazonaws.mobile.user.IdentityManager$AWSCredentialsProviderHolder.getCredentials(Unknown Source:61)
       at com.amazonaws.services.sns.AmazonSNSClient.invoke(Unknown Source:2818)
       at com.amazonaws.services.sns.AmazonSNSClient.setEndpointAttributes(Unknown Source:1455)
       at com.amazonaws.mobile.push.PushManager.setSNSEndpointEnabled(Unknown Source:289)
       at com.amazonaws.mobile.push.PushManager.setPushEnabled(Unknown Source:301)
`

**Comment by karthiksaligrama** [comment]
Steps to reproduce?

**Comment by alirezaafkar** [comment]
pushManager.registerDevice();
                if (pushManager.isRegistered()) {
                    pushManager.setPushEnabled(true);
                    for (Map.Entry<String, SnsTopic> entry : pushManager.getTopics().entrySet()) {
                        pushManager.subscribeToTopic(entry.getValue());
                    }
                }

**Comment by karthiksaligrama** [comment]
I just downloaded and tried a mobile hub sample, and i'm unable to reproduce the problem. Can you give me more information on how to reproduce this?

**Comment by alirezaafkar** [comment]
I can't reproduce it too! Happened for users and I've logs from Crashlyrics.

**Comment by karthiksaligrama** [comment]
the only way that i know of that this could have happened is when the network was lost when it was trying to refresh the cognito identity.
