### ISSUE TITLE
Pinpoint with AWS Mobile Hub initialize some times down.

### ISSUE THREAD

**Issue by teradonburiDely** [aws/aws-sdk-android#233]
* What service are you using?
Pinpoint with AWS Mobile Hub 

* In what version of SDK are you facing the problem?
Some times, app is down at app init.

* Is the issue limited to Simulators / Actual Devices?
Many devices...
SO-02H,SO-04H,SO-01H,
SC-02H,SC-05G,SC-04F,
SH-02G,305SH,SH-01G

* Can your problem be resolved if you bump to a higher version of SDK?
We use ver2.3.8.

* Is this problem related to specific Android/OS version?
Android 4,5,6

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
AWS Mobile Hub setup only pinpoint(GCM) → download sdk → setup amazonaws folder→setup with integration guide in app

```
public class YourApplication extends Application {
    private AbstractApplicationLifeCycleHelper applicationLifeCycleHelper;

    @Override
    public void onCreate() {
        super.onCreate();
        AWSMobileClient.initializeMobileClientIfNecessary(getApplicationContext());
        applicationLifeCycleHelper = new AbstractApplicationLifeCycleHelper(this) {
            @Override
            protected void applicationEnteredForeground() {
                final PinpointManager pinpointManager = AWSMobileClient.defaultMobileClient()
                    .getPinpointManager();
                pinpointManager.getSessionClient().startSession();
                // handle any events that should occur when your app has come to the foreground...
            }

            @Override
            protected void applicationEnteredBackground() {
                Log.d(LOG_TAG, "Detected application has entered the background.");
                final PinpointManager pinpointManager = AWSMobileClient.defaultMobileClient()
                    .getPinpointManager();
                pinpointManager.getSessionClient().stopSession();
                pinpointManager.getAnalyticsClient().submitEvents();
                // handle any events that should occur when your app has gone into the background...
            }
        };
    }

    @Override
    public void onTrimMemory(final int level) {
        Log.d(LOG_TAG, "onTrimMemory " + level);
        applicationLifeCycleHelper.handleOnTrimMemory(level);
        super.onTrimMemory(level);
    }
}
````

* Please include a stacktrace if applicable.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:456)
       at com.amazonaws.mobile.user.IdentityManager$AWSCredentialsProviderHolder.getCredentials(IdentityManager.java:61)
       at com.amazonaws.services.pinpoint.AmazonPinpointClient.invoke(AmazonPinpointClient.java:1783)
       at com.amazonaws.services.pinpoint.AmazonPinpointClient.updateEndpoint(AmazonPinpointClient.java:1594)
       at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient$1.run(TargetingClient.java:173)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by teradonburiDely** [comment]
Call next method for Mobile Analytics in Application class.
```
pinpointManager.getSessionClient().startSession();
```

Then,TargetingClient.java executeUpdate method call populateCredentialsWithCognito method in CognitoCredentialsProvider.java.
Sometime credentials.getExpiration() is null (not always).

```
try {
            result = cib.getCredentialsForIdentity(request);
        } catch (ResourceNotFoundException rnfe) {
            // If the identity id or identity pool is non-existant, this is
            // thrown
            result = retryGetCredentialsForIdentity();
        } catch (AmazonServiceException ase) {
            // If it's a corrupt id, then a validation exception is thrown
            if (ase.getErrorCode().equals("ValidationException")) {
                result = retryGetCredentialsForIdentity();
            }
            else {
                throw ase;
            }
        }

        com.amazonaws.services.cognitoidentity.model.Credentials credentials = result
                .getCredentials();
        sessionCredentials = new BasicSessionCredentials(credentials.getAccessKeyId(),
                credentials.getSecretKey(), credentials.getSessionToken());
        sessionCredentialsExpiration = credentials.getExpiration();
```

**Comment by karthiksaligrama** [comment]
related to #236
