### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Unknown URI: content://com.example/transfers/-1

### ISSUE THREAD

**Issue by kwatra** [aws/aws-sdk-android#239]
This is the same issue as #162 which was closed.

We faced the same issue. Looking at the TransferUtility code this could happen when the device is low on storage, or for some other reason SQLiteDatabase.insert() fails.

TransferUtility.[download()](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.java#L130) or upload() try to insert a transfer record via:
```
dbUtil.insertSingleTransferRecord()
```
which eventually write to the underlying SQLiteDB via SQLiteDatabase.insert(). This call can return -1 as the row ID on failure, which is saved in the URI path leading to a URI of form (see [link](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferDBBase.java#L111)):

content://com.example/transfers/-1

**Comment by minbi** [comment]
Hi kwatra,

Thank you for reporting this to us. I will relay your case to our team.

**Comment by karthiksaligrama** [comment]
@kwatra can you enable StrictMode policy and log the stacktrace and paste it here?

```
StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                .detectLeakedSqlLiteObjects()
                .detectLeakedClosableObjects()
                .penaltyLog()
                .build());
```

**Comment by snkashis** [comment]
@karthiksaligrama We're running into this issue as well.

**Comment by mlshon** [comment]
@snkashis do you have a stacktrace available?

**Comment by daxh** [comment]
Exactly the same situation. How to fix it ?

**Comment by kvasukib** [comment]
Hi @daxh,

Can you enable StrictMode policy and log the stack-trace and paste it here?

**Comment by kwatra** [comment]
Sorry, I don't have a stack trace available and it is hard to reproduce the error as it happens only when an SQLiteDatabase.insert() fails due to low storage or such.

As I had mentioned before if you look at the code, TransferUtility.download() or upload() try to insert a transfer record via:

`dbUtil.insertSingleTransferRecord()`

which eventually write to the underlying SQLiteDB via SQLiteDatabase.insert(). This call can return -1 as the row ID on failure, which is saved in the URI path leading to a URI of form:

content://com.example/transfers/-1

**Comment by daxh** [comment]
The problem is that I don't have any stacktrace as I see this problem from Crashlytics, it is happening somewhere on devices of users.

**Comment by amanflo** [comment]
```
java.lang.IllegalArgumentException: Unknown URI: content://com.ouwt.app.stag/transfers/-1
                                                                          at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBBase.query(TransferDBBase.java:149)
                                                                          at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.queryTransferById(TransferDBUtil.java:431)
                                                                          at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.getTransferById(TransferDBUtil.java:695)
                                                                          at com.amazonaws.mobileconnectors.s3.transferutility.TransferService.execCommand(TransferService.java:310)
                                                                          at com.amazonaws.mobileconnectors.s3.transferutility.TransferService$UpdateHandler.handleMessage(TransferService.java:220)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                          at android.os.Looper.loop(Looper.java:193)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
```

This is stacktrace where I am getting exception. Anyhelp?

**Comment by kvasukib** [comment]
Hello all, We have fixed bugs and made some improvements to `TransferUtility` in 2.6.16. Can you please upgrade to the latest and see if this fixes the issue?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
