### ISSUE TITLE
crash when using deeplinking

### ISSUE THREAD

**Issue by rubinbasha** [aws/aws-sdk-android#246]
greetings.

I would like to report an issue I just had now in with pinpoint. I created a campaign and there i sent the push with a deeplink with "myAppSchema". The issue is that if I do by mistake change the case of the schema and make it "MyAppSchema" than the app does get the notification but when clicking the notification than it crashes with this log:

`E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                  Process: my.app.pinpoint, PID: 2390
                  android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=MyAppSchema://news/1763 flg=0x10000000 }
                      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
                      at android.app.ContextImpl.startActivity(ContextImpl.java:791)
                      at android.app.ContextImpl.startActivity(ContextImpl.java:768)
                      at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
                      at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.NotificationClient.openURL(NotificationClient.java:540)
                      at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.NotificationClient.handleNotificationOpen(NotificationClient.java:600)
                      at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.NotificationClient.handleCampaignPush(NotificationClient.java:634)
                      at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.NotificationClient.handleGCMCampaignPush(NotificationClient.java:577)
                      at my.app.pinpoint.push.GcmMessageHandler.onMessageReceived(GcmMessageHandler.java:38)
                      at com.google.android.gms.gcm.GcmListenerService.zzt(Unknown Source)
                      at com.google.android.gms.gcm.GcmListenerService.zzk(Unknown Source)
                      at com.google.android.gms.gcm.GcmListenerService.zza(Unknown Source)
                      at com.google.android.gms.gcm.GcmListenerService$1.run(Unknown Source)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)`

How are we supposed to protect against this use case? Should we probably just not receive the push or be shown the notification at all since the schema is not correct, or should it be handled somehow?

**Comment by azsolinsky** [comment]
The issue has been corrected in the 2.3.9 Release. See the release notes for more details: https://aws.amazon.com/releasenotes/1894188094590101
