### ISSUE TITLE
Crash on AWSCredentialsProviderHolder.getCredentials()

### ISSUE THREAD

**Issue by rubinbasha** [aws/aws-sdk-android#247]
Greetings,

We have implemented the sdk in android and we currently have some random crashes with te sdk internal code. A call is made to AWSCredentialsProviderHolder.getCredentials() and it results in a NullPointerException which is not caught or handled. We can add a try catch ourselves at "com.amazonaws.mobile.user.IdentityManager$AWSCredentialsProviderHolder.getCredentials(IdentityManager.java:61)", but than we do not know what would be the consequences and what we should return in that method if the Exception happens. Please provide us with a solution or workaround for the time being.

`E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
                  Process: de.rtl2apps.berlintn, PID: 11479
                  java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
                      at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:456)
                      at com.amazonaws.mobile.user.IdentityManager$AWSCredentialsProviderHolder.getCredentials(IdentityManager.java:61)
                      at com.amazonaws.services.pinpoint.AmazonPinpointClient.invoke(AmazonPinpointClient.java:1783)
                      at com.amazonaws.services.pinpoint.AmazonPinpointClient.updateEndpoint(AmazonPinpointClient.java:1594)
                      at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient$1.run(TargetingClient.java:173)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)`

**Comment by rubinbasha** [comment]
The issue looks like it is happening only on the first run of the application and even than it is random. To reproduce that i tried many times , install , run and than uninstall and than the same again until i would get the crash in my device.

**Comment by azsolinsky** [comment]
A likely root cause synchronization issue has been identified related to this issue. We will update this issue again once the issue has been corrected.

**Comment by azsolinsky** [comment]
This synchronization issue has been corrected in AWS SDK for Android 2.3.9 Release. See the release notes for more details: https://aws.amazon.com/releasenotes/1894188094590101

**Comment by lutfiseptian** [comment]
i have problem can you help my problem sir Attempt to invoke virtual method 'com.savvi.rangedatepicker.CalendarPickerView$FluentInitializer com.savvi.rangedatepicker.CalendarPickerView.init(java.util.Date, java.util.Date)' on a null
