### ISSUE TITLE
AmazonClientException pausing and resuming quickly after uploading large file.

### ISSUE THREAD

**Issue by thomasaw** [aws/aws-sdk-android#248]
I'm running into exception pausing and resuming quickly after starting to upload a large file. The exception appears to be more likely the larger the file is (100MB+), but I've seen the problem also occur with 10MB files. Modifying the S3TransferUtilitySample `UploadActivity.beginUpload()` method to something like this reproduces the problem.

        TransferObserver observer = transferUtility.upload(Constants.BUCKET_NAME, file.getName(),
                file);
        transferUtility.pause(observer.getId());
        transferUtility.resume(observer.getId());

The problem occurs with v2.2.x of the aws-sdk-android, but it still occurs with v2.3.x of the aws-sdk-android.

If pausing is skipped, the problem doesn't occur.

The stacktrace (from v2.2.x) appears as follows:

      com.amazonaws.AmazonClientException: Unable to execute HTTP request: null
          at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:424)
          at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
          at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4375)
          at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3287)
          at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.initiateMultipartUpload(UploadTask.java:252)
          at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:100)
          at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:80)
          at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:44)
          at java.util.concurrent.FutureTask.run(FutureTask.java:237)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
          at java.lang.Thread.run(Thread.java:818)
      Caused by: java.io.InterruptedIOException
          at com.android.okio.Deadline.throwIfReached(Deadline.java:56)
          at com.android.okio.Okio$1.write(Okio.java:67)
          at com.android.okio.RealBufferedSink.flush(RealBufferedSink.java:154)
          at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.flush(HttpConnection.java:297)
          at com.android.okio.RealBufferedSink.flush(RealBufferedSink.java:156)
          at com.android.okio.RealBufferedSink$1.flush(RealBufferedSink.java:137)
          at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:130)
          at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
          at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:356)
          ... 11 more

**Comment by mlshon** [comment]
Thank you for reporting! 
We will look into this.

**Comment by kvasukib** [comment]
Hi @thomasaw, 

Thanks for reporting to us.

I tried this in 2.3.x and 2.6.x version and I couldn't reproduce the issue. I tried files of different sizes till 200MB. 

What version of Android are you using? Are these transfers happening over WiFi or Cellular?
Are there any network glitches observed while the transfer is going on?

**Comment by kvasukib** [comment]
Hi @homasaw,, We have fixed bugs and made some improvements to `TransferUtility` in 2.6.16. Can you please upgrade to the latest and see if this fixes the issue?

**Comment by kvasukib** [comment]
@thomasaw We have improved the stability of `TransferUtility` in 2.7.0. Please upgrade and let us know if it fixes the issue.
