### ISSUE TITLE
CRC32MismatchException reappeared 

### ISSUE THREAD

**Issue by navybk** [aws/aws-sdk-android#250]
[As decribed in issue 41](https://github.com/aws/aws-sdk-android/issues/41) 

A CRC32MismatchException was raised by DynamoDb, Release 2.3.9 (latest by now) on different devices with different Android versions installed.
```
DynamoDBQueryExpression<Class> queryExpression = new DynamoDBQueryExpression<Class>()
                .withHashKeyValues(Object)
                .withConsistentRead(false)
                .withLimit(100);

        List mList  = mapper.query(Class.class, queryExpression);
```

Exception:
```
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
                  Process: com.tool, PID: 2627
                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:325)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                      at java.lang.Thread.run(Thread.java:761)
                   Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Client calculated crc32 checksum didn't match that calculated by server side
                      at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:430)
                      at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200)
                      at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:4181)
                      at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:1450)
                      at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.PaginatedQueryList.fetchNextPage(PaginatedQueryList.java:84)
                      at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.PaginatedList.loadNextResults(PaginatedList.java:162)
                      at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.PaginatedList.nextResultsAvailable(PaginatedList.java:149)
                      at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.PaginatedList.loadAllResults(PaginatedList.java:133)
                      at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.PaginatedList.size(PaginatedList.java:417)
                      at DynamoDBAsyncTask.doInBackground(DynamoDBAsyncTask.java:88)
                      at DynamoDBAsyncTask.doInBackground(DynamoDBAsyncTask.java:27)
                      at android.os.AsyncTask$2.call(AsyncTask.java:305)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                      at java.lang.Thread.run(Thread.java:761) 
                   Caused by: com.amazonaws.internal.CRC32MismatchException: Client calculated crc32 checksum didn't match that calculated by server side
                      at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:119)
                      at com.amazonaws.http.JsonResponseHandler.handle(JsonResponseHandler.java:47)
                      at com.amazonaws.http.AmazonHttpClient.handleResponse(AmazonHttpClient.java:639)
                      at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:372)
                      at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200) 
                      at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:4181) 
                      at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.query(AmazonDynamoDBClient.java:1450) 
                      at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.PaginatedQueryList.fetchNextPage(PaginatedQueryList.java:84) 
                      at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.PaginatedList.loadNextResults(PaginatedList.java:162) 
                      at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.PaginatedList.nextResultsAvailable(PaginatedList.java:149) 
                      at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.PaginatedList.loadAllResults(PaginatedList.java:133) 
                      at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.PaginatedList.size(PaginatedList.java:417) 
                      at DynamoDBAsyncTask.doInBackground(DynamoDBAsyncTask.java:88) 
                      at DynamoDBAsyncTask.doInBackground(DynamoDBAsyncTask.java:27) 
                      at android.os.AsyncTask$2.call(AsyncTask.java:305) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                      at java.lang.Thread.run(Thread.java:761) 
```

**Comment by minbi** [comment]
Hi navybk,

This does not seem to be related to  the 2.3.9 release.
Thank you for reporting this issue; we will look into it.

**Comment by ankitpise** [comment]
@minbi I faced same issue today with 2.3.9 with Android 7+ version. Works fine on lower versions.

**Comment by tajchert** [comment]
I'm also struggling with this issue, is there any workaround for time to fix it permanently?

**Comment by karthiksaligrama** [comment]
We made some minor modifications with sdk version 2.4.1. Can you try that sdk and see if it fixes the problem

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
