### ISSUE TITLE
SSLException during upload part: I/O error during system call

### ISSUE THREAD

**Issue by ppamorim** [aws/aws-sdk-android#262]
* What service are you using?

Amazon S3

* In what version of SDK are you facing the problem?

Using Kotlin.

`com.amazonaws:aws-android-sdk-core:2.3.9`
`com.amazonaws:aws-android-sdk-s3:2.3.9`

* Is the issue limited to Simulators / Actual Devices?

No, happens randomly.

* Can your problem be resolved if you bump to a higher version of SDK?

All devices are API >= 21

* Is this problem related to specific Android/OS version?

No.

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Stable connection or not, this code works 95% of the time, but sometimes not. `Credential` is not empty or invalid (this is a fresh one). The only thing that doesn't change is the `uploadID`.

This is a very simple example:

```Kotlin
try {

  //...
  val s3Client = s3Client = AmazonS3Client(BasicSessionCredentials(
            credential.accessKeyId,
            credential.secretAccessKey,
            credential.sessionToken))

  val result = s3Client.initiateMultipartUpload(
            InitiateMultipartUploadRequest(credential.bucketName, credential.key))

  val uploadRequest = UploadPartRequest()
    .withBucketName(credential.bucketName)
    .withKey(credential.key)
    .withUploadId(credential.uploadId)
    .withFile(file) //File not empty
    .withPartNumber(partNumber)
    .withFileOffset(offset)
    .withPartSize(partSize)

  val uploadPartResult = s3Client.uploadPart(uploadRequest) //AmazonClientException and SSLException

  //...complete MultiPartUpload is not important for this problem.

}  catch (e: Exception) {
  e.printStackTrace()
}
```

* Please include a stacktrace if applicable.

```
 com.amazonaws.AmazonClientException: Unable to execute HTTP request: Write error: ssl=0xb9104118: I/O error during system call, Connection reset by peer
03-02 19:18:49.461 W:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:430)
03-02 19:18:49.461 W:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200)
03-02 19:18:49.461 W:     at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4375)
03-02 19:18:49.462 W:     at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3454)
...
03-02 19:18:49.462 W:     at com.b.a.a.f$1.run(ThreadExecutor.java:56)
03-02 19:18:49.462 W:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
03-02 19:18:49.462 W:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-02 19:18:49.462 W:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
03-02 19:18:49.462 W:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
03-02 19:18:49.462 W:     at java.lang.Thread.run(Thread.java:818)
03-02 19:18:49.462 W: Caused by: javax.net.ssl.SSLException: Write error: ssl=0xb9104118: I/O error during system call, Connection reset by peer
03-02 19:18:49.463 W:     at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
03-02 19:18:49.463 W:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:765)
03-02 19:18:49.463 W:     at com.android.okio.Okio$1.write(Okio.java:70)
03-02 19:18:49.463 W:     at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
03-02 19:18:49.463 W:     at com.android.okio.RealBufferedSink.write(RealBufferedSink.java:44)
03-02 19:18:49.463 W:     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:291)
03-02 19:18:49.463 W:     at com.android.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:116)
03-02 19:18:49.463 W:     at com.android.okio.RealBufferedSink$1.write(RealBufferedSink.java:131)
03-02 19:18:49.463 W:     at com.amazonaws.http.UrlHttpClient.write(UrlHttpClient.java:245)
03-02 19:18:49.463 W:     at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:165)
03-02 19:18:49.463 W:     at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:70)
03-02 19:18:49.463 W:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:360)
```

Offtopic: I noticed that some of the eTags are similar, look:

![log](https://cloud.githubusercontent.com/assets/5521682/23525144/587f5100-ff85-11e6-9e72-609a46f1ed47.png)

Why this is happening? This log comes from the result of method `s3Client.uploadPart(uploadRequest)`, so this is something that the SDK is returning to me.

**Comment by karthiksaligrama** [comment]
can you give me steps to reproduce? Or do you have some metrics on the network latency, connection type that you are seeing this error on etc?

**Comment by karthiksaligrama** [comment]
assuming resolved. please reopen if the issue persists with the steps to reproduce

**Comment by martinflorek** [comment]
@karthiksaligrama I am encountering this exact same "Connection reset by peer" issue when uploading to a pre-signed URL. It happens always with files around 1.8MiB. I have not tried smaller ones.

I am not using the SDK though, just OkHttp only (v 3.9.1). When I tried Java's `HttpURLConnection` it is working perfectly. So this looks like an issue with OkHttp.

**Comment by kvasukib** [comment]
Hi @martinflorek,

Thank you for sharing the information. Can you post a code snippet where you generate a preSignedURL and using it with OkHttp and HttpURLConnection?

Thanks

**Comment by martinflorek** [comment]
@kvasukib I have asked a question about this issue on [StackOverflow with full code.](https://stackoverflow.com/questions/48504394/upload-to-pre-signed-s3-url-fails-with-okhttp)

Here is the server JavaScript to generate the pre-signed URL:
```
const s3 = new aws.S3({
    region: 'us-west-2',
     signatureVersion: 'v4'
});
const signedUrlExpireSeconds = 60 * 5;

const signedUrl = s3.getSignedUrl('putObject', {
    Bucket: config.bucket.name,
    Key: `${fileName}`,
    Expires: signedUrlExpireSeconds
});
```

here the Android version with HttpURLConnection in Kotlin (inspired by the AWS documentation):
```
private fun uploadFileRaw(file: Uri, uploadUrl: String, contentResolver: ContentResolver) : Int {
    val url = URL(uploadUrl)
    val connection = url.openConnection() as HttpURLConnection
    connection.doOutput = true
    connection.requestMethod = "PUT"
    val out = connection.outputStream

    contentResolver.openInputStream(file).use {
        it.copyTo(out)
    }

    out.close()
    return connection.responseCode
}
```

and the simplified OkHttp version:
```
val s3UploadClient = OkHttpClient().newBuilder()
    .connectTimeout(30_000L, TimeUnit.MILLISECONDS)
    .readTimeout(30_000L, TimeUnit.MILLISECONDS)
    .writeTimeout(60_000L, TimeUnit.MILLISECONDS)
    .retryOnConnectionFailure(true)
    .build()

val body: RequestBody = UriRequestBody(file, contentResolver)
val request = Request.Builder()
        .url(uploadUrl)
        .put(body)
        .build()

s3UploadClient.newCall(request).execute()
```

Full details and more code is in the SO question.

**Comment by martinflorek** [comment]
@kvasukib did my code help?

**Comment by HamzaFarooqi9211** [comment]
For those facing this issue in React Native S3 upload (Large file)
Just go to S3 bucket-> Choose Bucket-> Permissions -> Change Block All Public Access to -> OFF (According to your need)
