### ISSUE TITLE
Amazon S3 SDK setAccelerateModeEnabled() will cause the upload to fail 

### ISSUE THREAD

**Issue by LOLHenry** [aws/aws-sdk-android#264]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Amazon S3
* In what version of SDK are you facing the problem?
2.3.9
* Is the issue limited to Simulators / Actual Devices?
Both
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific Android/OS version?
All Android.
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Using AWS S3 Sample android version:
https://github.com/awslabs/aws-sdk-android-samples/tree/master/S3TransferUtilitySample
Setting correct pool id, bucket id, region(EU_CENTRAL_1)
Change Code in Utils.java to this:
` public static AmazonS3Client getS3Client(Context context) {
        if (sS3Client == null) {
            System.setProperty(SDKGlobalConfiguration.ENFORCE_S3_SIGV4_SYSTEM_PROPERTY, "true");
            sS3Client = new AmazonS3Client(getCredProvider(context.getApplicationContext()));
            sS3Client.setRegion(Region.getRegion(Regions.EU_CENTRAL_1));
            sS3Client.setS3ClientOptions(S3ClientOptions.builder().setAccelerateModeEnabled(true).build());
        }
        return sS3Client;
    }`

if I disable the line:
`//sS3Client.setS3ClientOptions(S3ClientOptions.builder().setAccelerateModeEnabled(true).build());`

the Upload will be successful.

If I enable the line:
`sS3Client.setS3ClientOptions(S3ClientOptions.builder().setAccelerateModeEnabled(true).build());`
The Upload will be failed, and produce the stacktrace:

awsdemo E/UploadActivity﹕ Error during upload: 222
    com.amazonaws.services.s3.model.AmazonS3Exception: The authorization header is malformed; the region 'accelerate' is wrong; expecting 'eu-central-1' (Service: Amazon S3; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: A593B1A9467CE438), S3 Extended Request ID: bQuGLjXIJjcmEtFNY4CPWja3VMjkMsRzvTUZ7FDPkmsQRiPGlZgEPitm9n1UxcwaDXGeZjUjURc=
            at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:720)
            at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:394)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200)
            at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4375)
            at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3287)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.initiateMultipartUpload(UploadTask.java:252)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:100)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:80)
            at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:44)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

**Comment by karthiksaligrama** [comment]
@LOLHenry  can you please fill in the requested details?

**Comment by karthiksaligrama** [comment]
@LOLHenry  thanks for the update, we will fix this in the next release.

**Comment by karthiksaligrama** [comment]
resolved with 2.4.0
