### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory during AmazonS3Client initialization

### ISSUE THREAD

**Issue by pasku** [aws/aws-sdk-android#265]
* What service are you using?

  **Amazon S3**

* In what version of SDK are you facing the problem?

```
com.amazonaws:aws-android-sdk-core:2.3.9
com.amazonaws:aws-android-sdk-s3:2.3.9
```

* Is the issue limited to Simulators / Actual Devices?

    **No**

* Can your problem be resolved if you bump to a higher version of SDK?

   **No, API >= 21**

* Is this problem related to specific Android/OS version?

   **No**

```java
AmazonS3 s3 = new AmazonS3Client(new BasicAWSCredentials("XXX", "XXX"));
```

```
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory

	at com.amazonaws.AmazonWebServiceClient.<clinit>(AmazonWebServiceClient.java:58)
	at com.mycompany.test.S3DataSourceTest.testgetObjectSummaries(S3DataSourceTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more
```

**Comment by pasku** [comment]
I solved the problem adding testCompile 'commons-logging:commons-logging:1.1.1'.

**Comment by minbi** [comment]
This is the correct solution

**Comment by pasku** [comment]
@minbi It would be great if you can specify this on the docs, I didn't find anything related.

**Comment by karthiksaligrama** [comment]
@pasku I'm not sure why you should see the error, commons logging is declared as a dependency in the s3 maven Pom.xml file. Are you only seeing this in the test code or is the source code not compiling as well?

**Comment by pasku** [comment]
@karthiksaligrama In both.

**Comment by pasku** [comment]
```groovy
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"

    defaultConfig {
        applicationId "com.mycompany.app"
        minSdkVersion 10
        targetSdkVersion 25
        versionCode 1
        versionName "1.13.0"

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        debug {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/license.txt'
        exclude 'META-INF/notice.txt'
    }

    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            def outputFile = output.outputFile
            if (outputFile != null && outputFile.name.endsWith('.apk')) {
                def fileName = "release_watcher-${variant.buildType.name}.apk"
                output.outputFile = new File(outputFile.parent, fileName)
            }
        }
    }
}

// **************** MAVEN **************** //
apply plugin: 'maven'

artifacts {
    archives file:file("${project.buildDir}/outputs/apk/release_watcher-debug.apk"), classifier:"DEBUG"
}

afterEvaluate {
    uploadArchives.dependsOn('assembleDebug')
}
// *************************************** //

repositories {
    jcenter()
}

dependencies {
    compile 'com.android.support:support-v4:25.0.1'
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:design:25.0.1'
    compile 'com.android.support:recyclerview-v7:25.0.1'
    compile 'com.amazonaws:aws-android-sdk-core:2.3.9'
    compile 'com.amazonaws:aws-android-sdk-s3:2.3.+'
    testCompile 'commons-logging:commons-logging:1.1.1'

    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testCompile 'junit:junit:4.12'
    testCompile 'org.assertj:assertj-core:3.6.2'
}
```

**Comment by emumair** [comment]
Facing same issue for SDK version 28.
Runs well on version <= 27 but throws exception when app is run on version 28.

`testCompile 'commons-logging:commons-logging:1.1.1'`
OR
`testImplementation 'commons-logging:commons-logging:1.1.1'`
both are not working.

Using `implementation 'commons-logging:commons-logging:1.1.1'` is not allowed as build is failed..

**Comment by davinctor** [comment]
@emumair I think this problem related to x86 architecture. Because I also ran on Android Emulator x86 arch and it fails, but on the device works well.

**Comment by elliott-accolade** [comment]
Running on a Pixel XL 2 w/ API 28, still have the same issue.

**Comment by emezias** [comment]
The NoClassDef on the commons logging library is a crash problem with Android 9. This issue should be reopened

**Comment by minbi** [comment]
Please comment on #476 , locking
