### ISSUE TITLE
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Write error: ssl=0xd1386100: I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by wangshaolei** [aws/aws-sdk-android#273]
### com.amazonaws.AmazonClientException: Unable to execute HTTP request: Write error: ssl=0xd1386100: I/O error during system call, Connection reset by peer

 com.amazonaws.AmazonClientException: Unable to execute HTTP request: Write error: ssl=0xd1386100: I/O error during system call, Connection reset by peer
03-30 11:00:53.205 5302-5302/video.york.com.yorkvideo W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:424)
03-30 11:00:53.205 5302-5302/video.york.com.yorkvideo W/System.err:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:199)
03-30 11:00:53.205 5302-5302/video.york.com.yorkvideo W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4375)
03-30 11:00:53.205 5302-5302/video.york.com.yorkvideo W/System.err:     at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1704)
03-30 11:00:53.205 5302-5302/video.york.com.yorkvideo W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:203)
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:85)
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:44)
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err:     at java.lang.Thread.run(Thread.java:818)
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err: Caused by: javax.net.ssl.SSLException: Write error: ssl=0xd1386100: I/O error during system call, Connection reset by peer
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:771)
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err:     at com.android.okhttp.okio.Okio$1.write(Okio.java:76)
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err:     at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err:     at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
03-30 11:00:53.206 5302-5302/video.york.com.yorkvideo W/System.err:     at com.android.okhttp.okio.RealBufferedSink.write(RealBufferedSink.java:46)
03-30 11:00:53.207 5302-5302/video.york.com.yorkvideo W/System.err:     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:302)
03-30 11:00:53.207 5302-5302/video.york.com.yorkvideo W/System.err:     at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
03-30 11:00:53.207 5302-5302/video.york.com.yorkvideo W/System.err:     at com.android.okhttp.okio.RealBufferedSink$1.write(RealBufferedSink.java:198)
03-30 11:00:53.207 5302-5302/video.york.com.yorkvideo W/System.err:     at com.amazonaws.http.UrlHttpClient.write(UrlHttpClient.java:172)
03-30 11:00:53.207 5302-5302/video.york.com.yorkvideo W/System.err:     at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:129)
03-30 11:00:53.207 5302-5302/video.york.com.yorkvideo W/System.err:     at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
03-30 11:00:53.207 5302-5302/video.york.com.yorkvideo W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:356)
03-30 11:00:53.207 5302-5302/video.york.com.yorkvideo W/System.err: 	... 10 more

my code:
compile 'com.amazonaws:aws-android-sdk-s3:2.2.+'
compile 'com.squareup.okhttp3:okhttp:3.2.0'
```java
final TransferUtility transferUtility = getTransferUtility(context);
final TransferObserver transferObserver = transferUtility.upload(BUCKET_NAME, srcFile.getName(), srcFile);
        transferObserver.setTransferListener(new TransferListener() {
            @Override
            public void onStateChanged(int id, TransferState state) {
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                progressDialog.setProgress((int) (bytesCurrent / 1024));
                progressDialog.setMax((int) (bytesTotal / 1024));
            }

            @Override
            public void onError(int id, Exception ex) {
                ex.printStackTrace();
            }
        });
```
###thanks

**Comment by wangshaolei** [comment]
hi 
change to compile 'com.amazonaws:aws-android-sdk-s3:2.2.4' 
and resolve it.thanks
