### ISSUE TITLE
java.lang.IllegalStateException: Transfer failed.

### ISSUE THREAD

**Issue by wangshaolei** [aws/aws-sdk-android#274]
com.amazonaws.mobileconnectors.s3.transferutility.TransferObserver$TransferContentObserver.onChange(TransferObserver.java:194)

AmazonHttpClient: Unable to execute HTTP request: Write error: ssl=0xcffd7e40: I/O error during system call, Connection reset by peer
                                                                          javax.net.ssl.SSLException: Write error: ssl=0xcffd7e40: I/O error during system call, Connection reset by peer
                                                                              at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
                                                                              at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:771)
                                                                              at com.android.okhttp.okio.Okio$1.write(Okio.java:76)
                                                                              at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
                                                                              at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
                                                                              at com.android.okhttp.okio.RealBufferedSink.write(RealBufferedSink.java:46)
                                                                              at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:302)
                                                                              at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
                                                                              at com.android.okhttp.okio.RealBufferedSink$1.write(RealBufferedSink.java:198)
                                                                              at com.amazonaws.http.UrlHttpClient.write(UrlHttpClient.java:172)
                                                                              at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:129)
                                                                              at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
                                                                              at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
                                                                              at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
                                                                              at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4234)
                                                                              at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1644)
                                                                              at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:183)
                                                                              at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:73)
                                                                              at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:39)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at java.lang.Thread.run(Thread.java:818)

java.lang.IllegalStateException: Transfer failed.
03-30 11:54:12.373 5039-5039/video.york.com.yorkvideo W/System.err:     at com.amazonaws.mobileconnectors.s3.transferutility.TransferObserver$TransferContentObserver.onChange(TransferObserver.java:194)
03-30 11:54:12.373 5039-5039/video.york.com.yorkvideo W/System.err:     at android.database.ContentObserver.onChange(ContentObserver.java:130)
03-30 11:54:12.373 5039-5039/video.york.com.yorkvideo W/System.err:     at android.database.ContentObserver.onChange(ContentObserver.java:145)
03-30 11:54:12.373 5039-5039/video.york.com.yorkvideo W/System.err:     at android.database.ContentObserver$NotificationRunnable.run(ContentObserver.java:216)
03-30 11:54:12.373 5039-5039/video.york.com.yorkvideo W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
03-30 11:54:12.373 5039-5039/video.york.com.yorkvideo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-30 11:54:12.373 5039-5039/video.york.com.yorkvideo W/System.err:     at android.os.Looper.loop(Looper.java:148)
03-30 11:54:12.373 5039-5039/video.york.com.yorkvideo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
03-30 11:54:12.373 5039-5039/video.york.com.yorkvideo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-30 11:54:12.374 5039-5039/video.york.com.yorkvideo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-30 11:54:12.374 5039-5039/video.york.com.yorkvideo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-30 11:54:19.682 5039-5039/video.york.com.yorkvideo W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.

```java
compile 'com.amazonaws:aws-android-sdk-s3:2.2.4'
compile 'com.squareup.okhttp3:okhttp:3.2.0'
final TransferUtility transferUtility = getTransferUtility(context);
        final TransferObserver transferObserver = transferUtility.upload(BUCKET_NAME, srcFile.getName(), srcFile);
        transferObserver.setTransferListener(new TransferListener() {
            @Override
            public void onStateChanged(int id, TransferState state) {
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                progressDialog.setProgress((int) (bytesCurrent / 1024));
                progressDialog.setMax((int) (bytesTotal / 1024));
            }

            @Override
            public void onError(int id, Exception ex) {
                ex.printStackTrace();
            }
        });
```

thanks

**Comment by karthiksaligrama** [comment]
Connection reset by peer means that the server dropped your connection. This is not an SDK error per say. 

You could try updating your sdk to latest and see if that fixes your problem.

**Comment by wangshaolei** [comment]
@karthiksaligrama yes thanks, and I update the version 2.4.0 resolve it.
