### ISSUE TITLE
Read timeout error

### ISSUE THREAD

**Issue by virengujariya** [aws/aws-sdk-android#287]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
s3

* In what version of SDK are you facing the problem?
aws-android-sdk-s3:2.4.+

* Is the issue limited to Simulators / Actual Devices?
Only some Android devices

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
Probably 

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

* Please include a stacktrace if applicable.
```
Exception: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Read timed out
       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4624)
       at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1727)
       at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:206)
       at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:88)
       at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:47)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.net.SocketTimeoutException: Read timed out
       at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:745)
       at java.io.InputStream.read(InputStream.java:162)
       at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
       at com.android.okhttp.internal.Util.readAsciiLine(Util.java:316)
       at com.android.okhttp.internal.http.RawHeaders.fromBytes(RawHeaders.java:320)
       at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:147)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:795)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:347)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:499)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:140)
       at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:92)
       at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:85)
       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4624)
       at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1727)
       at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:206)
       at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:88)
       at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:47)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by minbi** [comment]
Hi @virengujariya ,

Do you have a code snippet that can reproduce this issue? and possibly a sample upload file that fails for you?

**Comment by minbi** [comment]
Feel free to re-open this issue if you want to further discuss
