### ISSUE TITLE
Error using CognitoCachingCredentialsProvider

### ISSUE THREAD

**Issue by anirudhbagri** [aws/aws-sdk-android#289]
I am trying to use CognitoCaCredentialsProvider.
I am using 2.4.1 version of AWS-core SDK.
I am trying to run this on Android Marshmallow.

```
CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                getApplicationContext(),
                "us-east-1:***%#$-df5a-4%^#-2457-0e41***efe39", // Identity Pool ID
                Regions.US_EAST_1 // Region
        );
```

Stack tree: 

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{in.amazonbusiness.berrio.android.app/com.sample.app.MainActivity}: java.lang.IllegalStateException: Unrecognized suffix for the AWS http client class name b
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                       Caused by: java.lang.IllegalStateException: Unrecognized suffix for the AWS http client class name b
                                                                                          at com.amazonaws.e.computeServiceName(Unknown Source)
                                                                                          at com.amazonaws.e.getServiceNameIntern(Unknown Source)
                                                                                          at com.amazonaws.e.computeSignerByURI(Unknown Source)
                                                                                          at com.amazonaws.e.setEndpoint(Unknown Source)
                                                                                          at com.amazonaws.i.a.b.init(Unknown Source)
                                                                                          at com.amazonaws.i.a.b.<init>(Unknown Source)
                                                                                          at com.amazonaws.i.a.b.<init>(Unknown Source)
                                                                                          at com.amazonaws.i.a.b.<init>(Unknown Source)
                                                                                          at com.amazonaws.a.s.<init>(Unknown Source)
                                                                                          at com.amazonaws.a.s.<init>(Unknown Source)
                                                                                          at com.amazonaws.a.q.<init>(Unknown Source)
                                                                                          at com.sample.app.MainActivity.onCreate(Unknown Source)
                                                                                          at android.app.Activity.performCreate(Activity.java:6251)
                                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
04-19 11:43:57.705 31086-31092/com.sample.app W/art: Suspending all threads took: 26.130ms

```

**Comment by minbi** [comment]
Hi @anirudhbagri ,

Can you provide some more code so that I can reproduce this? Are you obfuscating the class names?

**Comment by anirudhbagri** [comment]
This problem was solved.
I had to set 

`minifyEnabled false`

Any solution without setting it to false?? App size has grown up by 2 MB.

**Comment by rohandubal** [comment]
Your proguard configuration might be incorrect. Please refer to the proguard rules here: https://github.com/aws/aws-sdk-android/blob/master/Proguard.md
