### ISSUE TITLE
IotDataClient.getThingShadow() request signature error when running on API 25 device

### ISSUE THREAD

**Issue by dshalev** [aws/aws-sdk-android#293]
* What service are you using?
AWS-IOT

* In what version of SDK are you facing the problem?
2.4.2

* Is the issue limited to Simulators / Actual Devices?
Both simulator and actual device

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
Yes, same code runs with no error on API 23 device

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
`CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                context,
                COGNITO_POOL_ID, // Identity Pool ID
                MY_REGION // Region
        );
iotDataClient = new AWSIotDataClient(credentialsProvider);
String iotDataEndpoint = String.format("%s.iot.%s.amazonaws.com",
        CUSTOMER_SPECIFIC_ENDPOINT_PREFIX, MY_REGION.getName());
        iotDataClient.setEndpoint(iotDataEndpoint);
getThingShadowRequest = new GetThingShadowRequest()
                    .withThingName(THING_NAME);
GetThingShadowResult result =  iotDataClient.getThingShadow(getThingShadowRequest);`

Error:

> The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

* Please include a stacktrace if applicable.
`com.amazonaws.AmazonServiceException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AWSIotData; Status Code: 403; Error Code: ForbiddenException; Request ID: fa8bfda1-f60c-3416-6a09-fa2a1d672798)
                                                                           at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:720)
                                                                           at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:394)
                                                                           at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200)
                                                                           at com.amazonaws.services.iotdata.AWSIotDataClient.invoke(AWSIotDataClient.java:570)
                                                                           at com.amazonaws.services.iotdata.AWSIotDataClient.getThingShadow(AWSIotDataClient.java:405)
                                                                           at com.maatayim.wisebreeze2.networking.AWSClient$1.subscribe(AWSClient.java:87)
                                                                           at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
                                                                           at io.reactivex.Observable.subscribe(Observable.java:10514)
                                                                           at io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual(ObservableObserveOn.java:44)
                                                                           at io.reactivex.Observable.subscribe(Observable.java:10514)
                                                                           at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
                                                                           at io.reactivex.Scheduler$1.run(Scheduler.java:134)
                                                                           at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                           at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                           at java.lang.Thread.run(Thread.java:761)`

**Comment by bxpan** [comment]
Hi dshalev2,

Could you let us know if you're using one of the sample from aws-sdk-android-sample?  Has there been any change to your IAM policy or Cognito identity after you switched from API23 to API25 device ? 

Thanks.

**Comment by dshalev2** [comment]
Hi bxpan,

1. The code is similar to the temperature control sample.
2. There were no changes to the IAM policy or Cognito  identity, i have also created a new identity with  a new policy attached and using them didn't reproduced the same error.

Thanks.

**Comment by kvasukib** [comment]
Hi @dshalev2,

Can you check if the AWS Secret Access Key is correct for the user and the credentials that you are using?

**Comment by dshalev2** [comment]
Hi @kvasukib,
Access key is correct

**Comment by doc82** [comment]
Same happening here

**Comment by sunchunqiang** [comment]
Hi @dshalev 
Do you still have the issue with the latest SDK?

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.
