### ISSUE TITLE
Amazon S3 - Upload part error

### ISSUE THREAD

**Issue by akuholla** [aws/aws-sdk-android#297]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Amazon S3

* In what version of SDK are you facing the problem?
2.4.2

* Is the issue limited to Simulators / Actual Devices?
Actual deice

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
`TransferObserver observer = transferUtility.upload(
                    uploadInfo.getUploadBucketName(),
                    fileName,
                    file,
                    metadata
            );`
Uploading via Wifi, file size ~100MB

* Please include a stacktrace if applicable.

> `E/UploadPartTask: Encountered error uploading part 
                                                                               com.amazonaws.AmazonClientException: Unable to execute HTTP request: unexpected end of stream
                                                                                   at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
                                                                                   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
                                                                                   at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4624)
                                                                                   at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3641)
                                                                                   at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:49)
                                                                                   at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:29)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                   at java.lang.Thread.run(Thread.java:761)
                                                                                Caused by: java.net.ProtocolException: unexpected end of stream
                                                                                   at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.close(HttpConnection.java:314)
                                                                                   at com.android.okhttp.okio.RealBufferedSink.close(RealBufferedSink.java:241)
                                                                                   at com.android.okhttp.okio.RealBufferedSink$1.close(RealBufferedSink.java:209)
                                                                                   at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:177)
                                                                                   at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
                                                                                   at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
                                                                                   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
                                                                                   at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4624) 
                                                                                   at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3641) 
                                                                                   at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:49) 
                                                                                   at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:29) 
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                   at java.lang.Thread.run(Thread.java:761) `

**Comment by rohandubal** [comment]
Where is the file which is getting uploaded located? Does it only happen on files larger than 100Mb? Also, how frequently does it fail?

**Comment by binaryKarmic** [comment]
Where is the file which is getting uploaded located?
- S3 bucket ,region : us-west-2

Does it only happen on files larger than 100Mb? 
- No, It's happening for files as small as 24kb

Also, how frequently does it fail?
- For the device affected by this issue, its always.

**Comment by kvasukib** [comment]
Hi @akuholla,

Can you tell us how frequently are you facing this issue? What is the type, size, name, and metadata of the file you are trying to upload?  Typically, how many transfers are concurrent?

**Comment by kvasukib** [comment]
Hi @akuholla, We have fixed bugs and made some improvements to `TransferUtility` in 2.6.16. Can you please upgrade to the latest and see if this fixes the issue?
