### ISSUE TITLE
Timeout exception ForgotPasswordContinuation.continueTask() AWS Cognito

### ISSUE THREAD

**Issue by dbolgarchuk** [aws/aws-sdk-android#306]
I'm using Android AWS Cognito sdk for users authorization
aws-android-sdk-core:2.3.8
aws-android-sdk-cognito:2.3.8
aws-android-sdk-cognitoidentityprovider:2.3.8
When I try to reset password using, I'm ocassionally (about 25% of attempts) getting app crash

```
private ForgotPasswordContinuation mContinuation;

void proceedForgotPwd(final String email) {
    ClientConfiguration config = new ClientConfiguration();
        config.setConnectionTimeout(60000); //set timeout to 1 minute but crash occurs faster
        config.setSocketTimeout(60000);
    AmazonCognitoIdentityProviderClient identityProviderClient
                = new AmazonCognitoIdentityProviderClient(new AnonymousAWSCredentials(), config);
        identityProviderClient.setRegion(Region.getRegion(Regions.US_WEST_2));
    CognitoUserPool userPool = new CognitoUserPool(AuthActivity.this, userPoolId,
                clientId, null, identityProviderClient);
    CognitoUser user = userPool.getUser(email);
    
    user.forgotPasswordInBackground(new ForgotPasswordHandler() {
            @Override
            public void onSuccess() {
                // forgot pwd success, make auth
            }

            @Override
            public void getResetCode(ForgotPasswordContinuation continuation) {
                //getreset code success, showing confirmation code input field
            }

            @Override
            public void onFailure(Exception exception) {
                //this method is not called on crash
            }
        });
}


void applyCode() {
    mContinuation.setPassword(newPwd);
    mProgressListener.onLoadStarted();
    mContinuation.setVerificationCode(code);
    mContinuation.continueTask();
    //crash occurs after this call
}
```

Here's a stacktrace of crash:
```
com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:430)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200)
at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:2913)
at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.confirmForgotPassword(AmazonCognitoIdentityProviderClient.java:1127)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.confirmPasswordInternal(CognitoUser.java:556)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.access$400(CognitoUser.java:115)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$4.run(CognitoUser.java:497)
at java.lang.Thread.run(Thread.java:762)
Caused by: java.net.SocketTimeoutException: timeout
at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:221)
at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:239)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:104)
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1156)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:976)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:509)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:438)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:563)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java)
at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:86)
at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:80)
at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:360)
at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200) 
at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:2913) 
at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.confirmForgotPassword(AmazonCognitoIdentityProviderClient.java:1127) 
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.confirmPasswordInternal(CognitoUser.java:556) 
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.access$400(CognitoUser.java:115) 
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$4.run(CognitoUser.java:497) 
at java.lang.Thread.run(Thread.java:762) 
```

**Comment by mreddyg** [comment]
Hi,

Do you continue to see this exception during Forgot password process?
