### ISSUE TITLE
com.amazonaws.AmazonClientException: Unable to execute HTTP request: null - trying to generatePresignedUrl

### ISSUE THREAD

**Issue by ozv101** [aws/aws-sdk-android#317]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
CognitoCachingCredentialsProvider to get a presigned url

* In what version of SDK are you facing the problem?
2.4.5

* Is the issue limited to Simulators / Actual Devices?
Actual devices

* Can your problem be resolved if you bump to a higher version of SDK?
No. Im using the latest 2.4.5.

* Is this problem related to specific Android/OS version?
No. Happening on all OS and numerous devices.

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Can't reproduce. Only seeing the exception in Fabric.

* Please include a stacktrace if applicable.
 ```
com.amazonaws.AmazonClientException: Unable to execute HTTP request: null
       at com.amazonaws.http.AmazonHttpClient.afterError(Unknown Source)
       at com.amazonaws.http.AmazonHttpClient.execute(Unknown Source)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(Unknown Source)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(Unknown Source)
       at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(Unknown Source)
       at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(Unknown Source)
       at com.amazonaws.auth.CognitoCredentialsProvider.startSession(Unknown Source)
       at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(Unknown Source)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(Unknown Source)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(Unknown Source)
       at com.amazonaws.services.s3.AmazonS3Client.generatePresignedUrl(Unknown Source)
```

Related code: 
```
            CognitoCachingCredentialsProvider c = new CognitoCachingCredentialsProvider(
                    context.getApplicationContext(), 
                    "my_pool_id",   
                    Regions.US_EAST_2        
            );
     

        final AmazonS3 s3client = new AmazonS3Client(c);
        s3client.setEndpoint("s3.us-east-2.amazonaws.com");

        java.util.Date expiration = new java.util.Date();
        long msec = expiration.getTime();
        msec += 1000 * 60 * 60; // 1 hour.
        expiration.setTime(msec);

        final GeneratePresignedUrlRequest generatePresignedUrlRequest =
                new GeneratePresignedUrlRequest(bucketName, imageKey);
        generatePresignedUrlRequest.setMethod(HttpMethod.GET); // Default.
        generatePresignedUrlRequest.setExpiration(expiration);

        try {
            URL s = s3client.generatePresignedUrl(generatePresignedUrlRequest);
        } catch (AmazonClientException e) {
            Crashlytics.logException(e);
        }
```

**Comment by minbi** [comment]
Hi @ozv101 ,

Instead of `s3client.setEndpoint("s3.us-east-2.amazonaws.com");`
Can you try using `s3client.setRegion()`?
