### ISSUE TITLE
E/UploadTask: Failed to upload: 44 due to Unable to execute HTTP request: timeout

### ISSUE THREAD

**Issue by gagarinn** [aws/aws-sdk-android#324]
Hi!
I have issue with com.amazonaws.mobileconnectors.s3 
I use com.amazonaws:aws-android-sdk-core:2.4.0 and com.amazonaws:aws-android-sdk-s3:2.4.0
I have this issue only on LGE Nexus 5X Android 7.1.2 API 25

I try to upload video file (usually it size 15Mb)  sometimes file is aviable on server, but everytime I get:

07-23 11:10:50.577 8431-8431/my.trans E/FileUploadService: Error during upload: 44
                                                                    com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout
                                                                        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:430)
                                                                        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200)
                                                                        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4621)
                                                                        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1726)
                                                                        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:205)
                                                                        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:87)
                                                                        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:46)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                        at java.lang.Thread.run(Thread.java:761)
                                                                     Caused by: java.net.SocketTimeoutException: timeout
                                                                        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
                                                                        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:250)
                                                                        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                                        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                                                        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                                                        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                                                        at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
                                                                        at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                                                                        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
                                                                        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782)
                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
                                                                        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:517)
                                                                        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
                                                                        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java)
                                                                        at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:86)
                                                                        at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:80)
                                                                        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:360)
                                                                        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:200) 
                                                                        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4621) 
                                                                        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1726) 
                                                                        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:205) 
                                                                        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:87) 
                                                                        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:46) 
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                        at java.lang.Thread.run(Thread.java:761) 

Some examples from logcat:
1st:
07-23 11:10:33.658 8431-8431/my.trans E/FileUploadService: onProgressChanged: 44, total: 3893432, current: 0
07-23 11:10:35.249 8431-8431/my.trans E/FileUploadService: onProgressChanged: 44, total: 3893432, current: 131072
07-23 11:10:35.737 8431-8431/my.trans E/FileUploadService: onProgressChanged: 44, total: 3893432, current: 3893432
07-23 11:10:50.572 8431-8642/my.trans E/UploadTask: Failed to upload: 44 due to Unable to execute HTTP request: timeout
file is aviable!

2nd:
07-23 11:20:36.232 13271-13271/my.trans E/FileUploadService: onProgressChanged: 46, total: 4975062, current: 0
07-23 11:20:37.287 13271-13271/my.trans E/FileUploadService: onProgressChanged: 46, total: 4975062, current: 131072
07-23 11:20:48.685 13271-13271/my.trans E/FileUploadService: onProgressChanged: 46, total: 4975062, current: 4063232
07-23 11:20:48.775 13271-13271/my.trans E/FileUploadService: onProgressChanged: 46, total: 4975062, current: 4975062
07-23 11:21:03.742 13271-13465/my.trans E/UploadTask: Failed to upload: 46 due to Unable to execute HTTP request: timeout
file not abiable

3rd:
07-23 11:35:45.588 19144-19144/my.trans E/FileUploadService: onProgressChanged: 52, total: 7643603, current: 0
07-23 11:35:46.610 19144-19144/my.trans E/FileUploadService: onProgressChanged: 52, total: 7643603, current: 2531795
07-23 11:36:00.937 19144-19144/my.trans E/FileUploadService: onProgressChanged: 52, total: 7643603, current: 6332883
07-23 11:36:01.004 19144-19915/my.trans E/UploadPartTask: Encountered error uploading part Unable to execute HTTP request: timeout
07-23 11:36:05.642 19144-19144/my.trans E/FileUploadService: onProgressChanged: 52, total: 7643603, current: 6463955
07-23 11:36:25.652 19144-19144/my.trans E/FileUploadService: onProgressChanged: 52, total: 7643603, current: 7643603
07-23 11:36:40.679 19144-19144/my.trans E/FileUploadService: onProgressChanged: 52, total: 7643603, current: 7643603
07-23 11:36:40.701 19144-19914/my.trans E/UploadPartTask: Encountered error uploading part Unable to execute HTTP request: timeout
file not abiable

I tried setSocketTimeout() 30 sec, 60 sec and but it not solve a problem and uploading on other devices became very long.
Thanks.

**Comment by kvasukib** [comment]
Hi @gagarinn ,

Thanks for reporting to us.

1. Do you use WIFI / Cellular or just WIFI?
2. Is network availability disrupted during the transfer?

Thanks

**Comment by gagarinn** [comment]
Hi @kvasukib ,
Thanks for your reply.
    1. We use both.
    2. I will check it.
from last week everysing works good...
Thanks

**Comment by lamster2018** [comment]
same questions ,  upload file (over 500MB) can easy report this bug.
com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout

use wifi, network environment is good.
