### ISSUE TITLE
TransferDBBase (Deobfuscated class name)

### ISSUE THREAD

**Issue by liron-navon** [aws/aws-sdk-android#350]
* What service are you using?
aws s3 client for android

* In what version of SDK are you facing the problem?
```
    compile 'com.amazonaws:aws-android-sdk-core:2.6.2'
    compile 'com.amazonaws:aws-android-sdk-s3:2.6.2'
    compile 'com.amazonaws:aws-android-sdk-ddb:2.6.2'
```

* Is the issue limited to Simulators / Actual Devices?
Only on actual devices

* Can your problem be resolved if you bump to a higher version of SDK?
No, I'm using 2.6.2 which seems to be the highest current version

* Is this problem related to specific Android/OS version?
Seems like it's connected to this device since most of our clients don't have this problem:
Device: Xiaomi Redmi 4X
OS: 6.0.1

I'm not sure what made this happen, since I got the error from fabric and couldn't reproduce it in any way.

* Stacktrace
```
Fatal Exception: java.lang.IllegalStateException: attempt to re-open an already-closed object: SQLiteDatabase: /data/user/0/ui.bosco/databases/awss3transfertable.db
       at android.database.sqlite.SQLiteClosable.acquireReference(SQLiteClosable.java:55)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1312)
       at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
       at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBBase.query(Unknown Source)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.queryTransferById(Unknown Source)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferDBUtil.getTransferById(Unknown Source)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferService.execCommand(Unknown Source)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferService$UpdateHandler.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by kvasukib** [comment]
Hi @liron-navon,

Thanks for using our SDK and reporting to us. Sorry for the inconvenience caused.

What operations are you doing with S3? Approximately can you tell us the number of transfers that would be present in the database?

**Comment by liron-navon** [comment]
I use the s3 sdk to upload images and audio files, how can i access the
number of transfers from the database?

**Comment by kvasukib** [comment]
Hello @liron-navon,

Sorry for the delayed follow-up. 

1. You can access the database file at: /data/user/0/ui.bosco/databases/awss3transfertable.db as printed in the stack trace and copy from the device to your machine and do a line count.

2. Do you have an idea of the approximate number of transfers in each category? (Upload / Multi-part Upload / Download) when did this happen? You could get this from the DB file too.

3. When you call TransferUtiltity to upload/download a file, it sends a message to the TransferService with the transfer record Id. Transfer Service reads the transfer record from the database based on the id. As part of this, it does a SQL query with the ID and fetches the row pertaining to the ID.

The error you reported could happen in the following case where there is a race condition where one thread closed the database reference whereas the thread that errored out is trying to read from the database.
