### ISSUE TITLE
TransferManager on Android Oreo

### ISSUE THREAD

**Issue by ppamorim** [aws/aws-sdk-android#358]
* Question:

Is `TransferManager` ready to be used on Android Oreo? I did a analysis of the source code and I don't find any code treating the Foreground service. Is that correct? My app keeps crashing due this.

* What service are you using?

AWS S3

* In what version of SDK are you facing the problem?

2.6.6

* Is the issue limited to Simulators / Actual Devices?

No

* Can your problem be resolved if you bump to a higher version of SDK?

No

* Is this problem related to specific Android/OS version?

Yes, Android Oreo (27)

* Logcat:

```
E/AndroidRuntime: FATAL EXCEPTION: main
   Process: com.tpro.dictate, PID: 16843
   android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
   at android.os.Handler.dispatchMessage(Handler.java:106)
   at android.os.Looper.loop(Looper.java:164)
   at android.app.ActivityThread.main(ActivityThread.java:6494)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Thank you.

**Comment by minbi** [comment]
Hi @ppamorim ,

Transfer Manager is a deprecated class, please use Transfer Utility instead.
Are there features that are missing that prevent you from transitioning?
