### ISSUE TITLE
Aws Iot crash when it is reconnecting 

### ISSUE THREAD

**Issue by DaxiaK** [aws/aws-sdk-android#372]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Aws Iot

* In what version of SDK are you facing the problem?
2.4.4
* Is the issue limited to Simulators / Actual Devices?
I only test it on Nexus 7 (MRA58K Android6.0)
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific Android/OS version?
No
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

1.New a AWSIotMqttManager
```
AWSIotMqttManager mqttManager = new AWSIotMqttManager(MqttConfig.getClientId(), MqttConfig.getEndPoint());
```
2.Set forever retry between 1 second to 1 second (or 0  second to 0 second)
```
mqttManager.setAutoReconnect(true);
mqttManager.setMaxAutoReconnectAttepts(-1);
mqttManager.setReconnectRetryLimits(1, 1);
```
3.Connect the iot in a service
```
mqttController.connect(this);
```
4.Close the device Wi-Fi when iot is connected
5.After 475-480 retry times , I will get a crash.

The crash log is:
```
11-15 11:47:10.733 32334-3596/com.iottest E/art: ashmem_create_region failed for 'indirect ref table': Too many open files
11-15 11:47:10.733 32334-3596/com.iottest W/art: Throwing OutOfMemoryError "Could not allocate JNI Env"
11-15 11:47:10.828 32334-3596/com.iottest E/AndroidRuntime: FATAL EXCEPTION: Reconnect thread
                                                                              Process: com.iottest, PID: 32334
                                                                              java.lang.OutOfMemoryError: Could not allocate JNI Env
                                                                                  at java.lang.Thread.nativeCreate(Native Method)
                                                                                  at java.lang.Thread.start(Thread.java:1063)
                                                                                  at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.start(ClientComms.java:625)
                                                                                  at org.eclipse.paho.client.mqttv3.internal.ClientComms.connect(ClientComms.java:244)
                                                                                  at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(ConnectActionListener.java:186)
                                                                                  at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:592)
                                                                                  at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.reconnectToSession(AWSIotMqttManager.java:860)
                                                                                  at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$4.run(AWSIotMqttManager.java:924)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)

//Another log
11-15 13:30:12.565 7853-9902/com.iottest A/Looper: Could not create epoll instance.  errno=24
```

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by DaxiaK** [comment]
Hi,
I try to implement a workaround flow to avoid this problem.
In my first idea , I want to disconnect asw iot if network ,certificate or policy is wrong. This flow can reduce reconnect times. But I found the aws iot sdk doesn't provide "Throwable" when auto reconnect. Does any specification let aws iot sdk to keep it?
