### ISSUE TITLE
aws-android-sdk-auth-userpools does not support forced change password flow

### ISSUE THREAD

**Issue by akki1997** [aws/aws-sdk-android#374]
StackTrace-
FATAL EXCEPTION: main
                                                                         Process: com.example.aksshita.toll, PID: 4082
                                                                         java.lang.UnsupportedOperationException: Not supported in this sample.
                                                                             at com.amazonaws.mobile.auth.userpools.CognitoUserPoolsSignInProvider$6.authenticationChallenge(CognitoUserPoolsSignInProvider.java:331)
                                                                             at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$28.run(CognitoUser.java:2108)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by kvasukib** [comment]
Hi @akki1997,

Thanks for reporting to us. Are you trying to sign-in with the temporary password created by a UserPool Admin? The Amazon Cognito UserPools SDK (aws-sdk-android-cognitoidentityprovider) has the API that lets the user change password for the first time he signs in. But, the Auth UserPools SDK (aws-sdk-anroid-auth-userpools), which has the SignIn UI doesn't support the use case, where a user with temporary credentials signs in and requires changing the password. 

We will take it as a feature request.

For more information to signing-in as an admin created user, refer this documentation: http://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-android-sdk-authenticate-admin-created-user.html

**Comment by akki1997** [comment]
Yes I was signing in with the temporary password

**Comment by kvasukib** [comment]
Sorry for the inconvenience caused. Currently, the Auth UserPools SDK (aws-sdk-anroid-auth-userpools) with the SignIn UI doesn't support this use-case. We are taking it as a feature request.

**Comment by akki1997** [comment]
So how to proceed further

**Comment by akki1997** [comment]
How Delhi wants to commute to work
           
            
            
       
       
            
       
       
            
       
       
            
           
              
                “A developed country is not a place where the poor have cars. It's where the rich use public transportation.”― Gustavo PetroYour friend saurabh who takes Shuttl to work has nominated you for this initiative. Help us understand how you want to commute to work.
              
           
            
       

       
           



     



    
    Are you happy with the existing public transport in Delhi-NCR?
    



     


      
        

                
                    
                        
                            ◯
                            
                        
                            Yes
                        
                    
                
        
    

        
             
        

      
        

                
                    
                        
                            ◯
                            
                        
                            No
                        
                    
                
        
    

         
             
        

 
       
       
            
           
               Please do not forward this email as its survey link is unique to you. Unsubscribe from this list
           
            
       
       
            
       

       
           
    
        
            Powered by

**Comment by kredden** [comment]
Hi,

I'm not sure what you last post means?

Regards,
Kevin

**Comment by kopevgale** [comment]
who can explain how to remove the issue? I get the same error

**Comment by Nthalk** [comment]
Using the latest version, this still happens.

What's worse, is that the Cognito android tutorials will eventually lead you here (https://docs.aws.amazon.com/aws-mobile/latest/developerguide/getting-started.html)

The primary issue is that the Cognito user pool, when creating a user, defaults to an unchangeable status of "Enabled / FORCE_CHANGE_PASSWORD".

If your only endpoint is an Android application, then this will just crash your app every time it happens.

@kopevgale because of how this is implemented, it seems impossible to override this behavior.

You can, however get around this, buy not using UserPools and moving to OAUTH (which is what I'm about to do).

**Comment by danleahy** [comment]
Any update, just trying the tutorial myself, got the dreaded 
java.lang.UnsupportedOperationException: Not supported in this sample.
Error

What is the fix/workaround ?

**Comment by danleahy** [comment]
Just tried this different tutorial
https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-integrating-user-pools-android.html
demo doesn't use best practices, like putting the secret key in the app code?
just tried it and it doesn't crash

**Comment by iamdeadman** [comment]
Having the same issue here, did you manage to solve this issue with this itself - https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-integrating-user-pools-android.html

Or you found any alternatives for this issue ?

**Comment by pacifire** [comment]
Still facing the same issue & no workaround has been found.
At least Amazon AWS should help us here....

**Comment by ringonotts** [comment]
OK, so this all fails because the AWSStartupHandler does not have the authenticationChallenge callback implemented. Apparently this is a feature request now.<br><br>
@kvasukib tells us to have a look at
https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-user-identity-pools-android-sdk-authenticate-admin-created-user.html

This tells us 
> you must implement the AuthenticationChallenge callback method

As far as I can tell, AuthenticationChallenge is part of the the AuthenticationHandler interface. So i've implemented this as part of my main activity:
`public class MainActivity extends AppCompatActivity implements AuthenticationHandler{`

And then overidden the other API's as well as authenticationChallenge API.

However, i still get the same error. Any thoughts on what i'm doing wrong please ?

TIA, Ringo

**Comment by ringonotts** [comment]
I'm not sure why this was so hard to figure out but until this feature is fixed, then the guidance on the "welcome to Mobile AWS" (https://docs.aws.amazon.com/aws-mobile/latest/developerguide/add-aws-mobile-user-sign-in.html) should really be changed until this feature is fully implemented.

So, for future reference, and for any other poor sole just following instructions only to find out you get here, just take a look at the sample applications here:

https://github.com/awslabs/aws-sdk-android-samples

There is a great sample called "AmazonCognitoYourUserPoolsDemo" which works. Yes, its a lot more complicated (i.e. its normal), but it works.

HTH's..

**Comment by minbi** [comment]
Hi,

We are looking into this issue now.

**Comment by minbi** [comment]
Hi @akki1997 @kopevgale @Nthalk @danleahy @iamdeadman @pacifire @ringonotts ,

Please see if SDK release 2.7.6 fixes this issue for you. We have added the following enhancements:
- Preserve sign-up form fields when sign-up validation fails so that end-users can correct and try again.
- Automatically sign-in user after actions such as sign-up or forgot password.

You may see all changes in the [changelog](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md#release-276)

**Comment by minbi** [comment]
Hi,

We are closing this issue because there has been no activity. Please feel free to open a new issue if the problem persists. We ask this because closed issues are not actively monitored.

Thanks
