### ISSUE TITLE
Cognito 'device confirmation failed' error.

### ISSUE THREAD

**Issue by yalcinozdemir** [aws/aws-sdk-android#378]
Some Android devices can't register device to cognito upon login, so they have to login every time they want to use the android app. 

Cognito produces 'device confirmation failed' error. This error occurs on some devices but not on all devices. Also, cognito returns newDevice as null. We have selected auto remember on cognito  remember device option on AWS panel. Also, CognitoDeviceHelper.getDeviceKey and getDeviceSecret return null.

* What service are you using?
cognitoidentityprovider, , stacktraceyi yazdım slackten

* In what version of SDK are you facing the problem?
2.6.6

* Is the issue limited to Simulators / Actual Devices?
Actual Device

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
Android

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

When trying to login with a confirmed account. 

* Please include a stacktrace if applicable.
`E/CognitoUser: Device confirmation failed: 
com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoNotAuthorizedException: User is not authenticated
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession(CognitoUser.java:825)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.confirmDevice(CognitoUser.java:2627)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.handleChallenge(CognitoUser.java:2067)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.respondToChallenge(CognitoUser.java:1889)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.startWithUserSrpAuth(CognitoUser.java:1949)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.initiateUserAuthentication(CognitoUser.java:749)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.AuthenticationContinuation$1.run(AuthenticationContinuation.java:100)
at java.lang.Thread.run(Thread.java:818)
Caused by: com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Invalid Refresh Token. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 79c34bb2-d209-11e7-8124-51317dfd9dc4)
at com.amazonaws.http.AmazonHttpClient.a(AmazonHttpClient.java:729)
at com.amazonaws.http.AmazonHttpClient.b(AmazonHttpClient.java:405)
at com.amazonaws.http.AmazonHttpClient.a(AmazonHttpClient.java:212)
at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:2914)
at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.initiateAuth(AmazonCognitoIdentityProviderClient.java:2051)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.refreshSession(CognitoUser.java:1856)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession(CognitoUser.java:820)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.confirmDevice(CognitoUser.java:2627) 
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.handleChallenge(CognitoUser.java:2067) 
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.respondToChallenge(CognitoUser.java:1889) 
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.startWithUserSrpAuth(CognitoUser.java:1949) 
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.initiateUserAuthentication(CognitoUser.java:749) 
at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.AuthenticationContinuation$1.run(AuthenticationContinuation.java:100) 
at java.lang.Thread.run(Thread.java:818) `

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by greywolfhalil** [comment]
I have the same error. When I try sign in with confirmed user with LG G3, I'm getting this error. I was successfully sign in via lg g4 and samsung galaxy grand prime. But some devices getting me error same of this issue. Also getDeviceKey and getDeviceSecret null

**Comment by greywolfhalil** [comment]
Can someone help me ?

**Comment by mataide** [comment]
I figured out that its not a device specific problem. It happens for the same device. Sometimes it works, sometimes not.

I am trying to debug and give you more information.

**Comment by mataide** [comment]
This validation inside CognitoUserSession is the problem.
A valid token sometimes fails in this validation.

   ```
public boolean isValid() {
        final Date currentTimeStamp = new Date();

        try {
            return (currentTimeStamp.before(idToken.getExpiration())
                    & currentTimeStamp.before(accessToken.getExpiration()));
        } catch (final Exception e) {
            return false;
        }
    }
```

**Comment by mataide** [comment]
Sometimes it cant get the Expiration Date from idToken from the method:

CognitoAccessToken:
  ```
 /**
     * Returns expiration of this access token.
     *
     * @return access token expiration in UTC as java.util.Date object.
     */
    public Date getExpiration() {
        try {
            final String claim = CognitoJWTParser.getClaim(super.getToken(), "exp");
            if (claim == null) {
                return null;
            }
            final long epocTimeSec = Long.parseLong(claim);
            final long epocTimeMilliSec = epocTimeSec * SECS;
            return new Date(epocTimeMilliSec);
        } catch (final Exception e) {
            throw new CognitoInternalErrorException(e.getMessage());
        }
    }
```

**Comment by jarrrgh** [comment]
I had this same issue. Turned out my device time was not set to automatic and I had been testing some random dates earlier.
