### ISSUE TITLE
Downloads failing : Unable to execute HTTP request: unexpected end of stream on Connection

### ISSUE THREAD

**Issue by binaryKarmic** [aws/aws-sdk-android#381]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS S3 

* In what version of SDK are you facing the problem?
 2.2.13 , also same result with 2.4.0

* Is the issue limited to Simulators / Actual Devices?
Actual devices 

* Can your problem be resolved if you bump to a higher version of SDK?
No, tried it.

* Is this problem related to specific Android/OS version?
No, it's not. But observing this in some cases only. For example, the issue is arriving on particular devices only. 
Example :  
- On Wifi network, Android 7.1 and Android 6.0(OnePlus2), but another device running Android 7.1 (OnePlus 5t) on same wifi network was not working.
- On mobile data network, Android 4.4.2 (SM-G7102), Android 6.0.1(Redmi Note 3)

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
above answer will be helpful.

* Please include a stacktrace if applicable.

```
12-01 13:39:23.543 com.xxxxxx.xxxx I/AmazonHttpClient: Unable to execute HTTP request: unexpected end of stream on Connection{xxxx-appstorage.s3.amazonaws.com:443, proxy=DIRECT@ hostAddress=54.231.184.166 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1} (recycle count=0)
                                                              java.io.IOException: unexpected end of stream on Connection{xxxx-appstorage.s3.amazonaws.com:443, proxy=DIRECT@ hostAddress=54.231.184.166 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1} (recycle count=0)
                                                                  at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:210)
                                                                  at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                                                                  at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:905)
                                                                  at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:789)
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443)
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:497)
                                                                  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
                                                                  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:25)
                                                                  at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:72)
                                                                  at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:66)
                                                                  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
                                                                  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
                                                                  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4213)
                                                                  at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1112)
                                                                  at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:68)
                                                                  at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:34)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                  at java.lang.Thread.run(Thread.java:818)
                                                               Caused by: java.io.EOFException: \n not found: size=0 content=...
                                                                  at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
                                                                  at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
                                                                  at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80) 
                                                                  at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:905) 
                                                                  at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:789) 
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:443) 
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388) 
                                                                  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:497) 
                                                                  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109) 
                                                                  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:25) 
                                                                  at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:72) 
                                                                  at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:66) 
                                                                  at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353) 
                                                                  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196) 
                                                                  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4213) 
                                                                  at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1112) 
                                                                  at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:68) 
                                                                  at com.amazonaws.mobileconnectors.s3.transferutility.DownloadTask.call(DownloadTask.java:34) 
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                  at java.lang.Thread.run(Thread.java:818) 
12-01 13:39:23.544 com.xxxxx.xxxxx E/DownloadTask: Failed to download: 4 due to Unable to execute HTTP request: unexpected end of stream on Connection{xxxxx-appstorage.s3.amazonaws.com:443, proxy=DIRECT@ hostAddress=54.231.184.166 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1} (recycle count=0)
```

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by minbi** [comment]
Hi @binaryKarmic ,

Would you be able to try version 2.6.9 of the SDK? There were no breaking changes between 2.4.0 and now.

If you tried 2.4.0 and don't want to do to 2.6.x, then you should try 2.4.7 because there were many S3 bug fixes from 2.4.0-2.4.7.

Can you provide some more details about the file that you are downloading?
i.e. size, name, type, and metadata (in the S3 console)

**Comment by binaryKarmic** [comment]
Would you be able to try version 2.6.9 of the SDK?
- We tried updating to 2.6.9 too,  but still the same result.It didn`t help.

size - around 25kb
name - some_file_name_01.json
type - .json
metadata (in the S3 console) -  key : Content-Type   value : application/octet-stream

**Comment by kvasukib** [comment]
Hi @binaryKarmic,

Thanks for the reply.

I tried the following code and config:

CognitoCachingCredentialsProvider sCredProvider = new CognitoCachingCredentialsProvider(
                    context.getApplicationContext(),
                    "<COGNITO_POOL_ID>",
                    Regions.fromName("<COGNITO_POOL_REGION>"));

AmazonS3 sS3Client = new AmazonS3Client(sCredProvider);
sS3Client.setRegion(Region.getRegion(Regions.fromName("<BUCKET_REGION>")));

TransferUtility sTransferUtility = new TransferUtility(sS3Client);

TransferObserver observer = transferUtility.download("<BUCKET_NAME>", key, file);

On the S3 console, I created a file 'sample.json' of the following config on 2.3.9 and 2.6.9

'sample.json' 65MB Content-Type: 'application/octet-stream'
'sample.json' 500B Content-Type: 'application/octet-stream'
'sample.json' 65MB Content-Type: 'binary/octet-stream'
'sample.json' 500B Content-Type: 'binary/octet-stream'

and the download finished without an exception.

1. Can you post your code snippet to help us debug the issue?
2. How did you upload your file? When you uploaded, did you specify any metadata or encryption?
