### ISSUE TITLE
S3 doesObjectExist throws 403 Forbidden on one device.

### ISSUE THREAD

**Issue by njovy** [aws/aws-sdk-android#382]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using? S3

* In what version of SDK are you facing the problem? 2.6.9

* Is the issue limited to Simulators / Actual Devices? Actual Device SHV-E370 (4.2.2 API17)

* Can your problem be resolved if you bump to a higher version of SDK? No

* Is this problem related to specific Android/OS version? I guess. This problem only occurs on this device and I have tested on multiple devices running different versions(so far tested on 4.4, 5.x, 6.x, 7.x., 8.x with no problems)

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Call ```doesObjectExist``` to a file that has a proper permission. 
An expected response is a true or false but this throws 403 forbidden error. This exception was never thrown even if a key didn't exist.
I tested the same account on different devices to see if a permission is not properly set but it works as expected on other devices.

* Please include a stacktrace if applicable.
```
 com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: A508B950E6FA29CF), S3 Extended Request ID: PwJV6mVsG+/HKrXPAf/0AD3iUx0sxnYt7oF1cXFqDFHSmKMcNKOsMfU7vKBWLYsCLlQ8xBGsdIw=
                                                                                                                     at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:729)
                                                                                                                     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
                                                                                                                     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
                                                                                                                     at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4643)
                                                                                                                     at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1215)
                                                                                                                     at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1180)
                                                                                                                     at com.amazonaws.services.s3.AmazonS3Client.doesObjectExist(AmazonS3Client.java:1259)
```

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Hi @njovy,

Thanks for reporting to us. Can you provide some more details about the file that you are accessing?
i.e. size, name, type, and metadata (in the S3 console)

**Comment by njovy** [comment]
Hello @kvasukib,
The file doesn't exist at the moment. My android client checks key if a file has been already uploaded to prevent duplicated put requests. As I mentioned above, a permission is properly set so it returns false when a file doesn't exist on other devices.

**Comment by kvasukib** [comment]
Thank you @njovy for the reply. Sorry for the delayed response. 

As you discovered, Amazon S3 will return an AccessDenied error when a nonexistent key is requested and the requester is not allowed to list the contents of the bucket. By the Amazon S3 definition, not being allowed to list the contents of a bucket means not being allowed to discover whether a particular key exists. Returning NoSuchKey would leak information about the nonexistence of the requested key. Instead, Amazon S3 returns AccessDenied. AccessDenied does not say anything about the existence or nonexistence of the requested key, so no information is leaked.

Amazon S3 will return a NoSuchKey error when a nonexistent key is requested and the requester is allowed to list the contents of the bucket.

Do you have s3:List* permissions for the user? if so, you won't get 403, else you would.
