### ISSUE TITLE
Android and AWS Cognito, kinesis - Unable to send data to delivery stream when the apk is exported as release version

### ISSUE THREAD

**Issue by Sharathnasa** [aws/aws-sdk-android#393]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Cognito, Firehose kinesis

* In what version of SDK are you facing the problem?
    compile 'com.amazonaws:aws-android-sdk-core:2.6.10'
    compile 'com.amazonaws:aws-android-sdk-cognito:2.6.10'
    compile 'com.amazonaws:aws-android-sdk-s3:2.6.10'
    compile 'com.amazonaws:aws-android-sdk-kinesis:2.6.10'

* Is the issue limited to Simulators / Actual Devices?
   Actual device

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
No

The Problem i'm facing is explained as below.
I'am using the AWS Kinesis for Android. It works  perfectly fine on debug version of apk(data is transferring successfully  to the delivery stream through the kinesis firehose to s3),but when i build the release versions of apk, its not  happening. I'm  getting the below exception.

CognitoCachingCredentialsProvider: Failure to get credentials
                                   com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Token is not from a supported provider of this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: c3d5e109-f47e-11e7-a200-9df17adc0751)
                                                                                       at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(Unknown Source)
                                                                                       at com.amazonaws.http.AmazonHttpClient.executeHelper(Unknown Source)
                                                                                       at com.amazonaws.http.AmazonHttpClient.execute(Unknown Source)
                                                                                       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(Unknown Source)
                                                                                       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(Unknown Source)
                                                                                       at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(Unknown Source)
                                                                                       at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(Unknown Source)
                                                                                       at com.amazonaws.auth.CognitoCredentialsProvider.startSession(Unknown Source)
                                                                                       at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(Unknown Source)
                                                                                       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(Unknown Source)
                                                                                       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(Unknown Source)
                                                                                       at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.invoke(Unknown Source)
                                                                                       at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.putRecordBatch(Unknown Source)
                                                                                       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FirehoseRecordSender.sendBatch(Unknown Source)
                                                                                       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.AbstractKinesisRecorder.submitAllRecords(Unknown Source)
                                                                                       at io.fxpi.chidori.common.receiver.CommonBroadcastReceiver$2.run(Unknown Source)

another stack trace:
AbstractKinesisRecorder: ServiceException in submit all, the last request is presumed to be the cause and will be dropped
                                                                         com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Token is not from a supported provider of this identity pool. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: c40703ad-f47e-11e7-8699-d9ecd8110664)
                                                                             at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(Unknown Source)
                                                                             at com.amazonaws.http.AmazonHttpClient.executeHelper(Unknown Source)
                                                                             at com.amazonaws.http.AmazonHttpClient.execute(Unknown Source)
                                                                             at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(Unknown Source)
                                                                             at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(Unknown Source)
                                                                             at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(Unknown Source)
                                                                             at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(Unknown Source)
                                                                             at com.amazonaws.auth.CognitoCredentialsProvider.startSession(Unknown Source)
                                                                             at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(Unknown Source)
                                                                             at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(Unknown Source)
                                                                             at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(Unknown Source)
                                                                             at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.invoke(Unknown Source)
                                                                             at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.putRecordBatch(Unknown Source)
                                                                             at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FirehoseRecordSender.sendBatch(Unknown Source)
                                                                             at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.AbstractKinesisRecorder.submitAllRecords(Unknown Source)
                                                                             at io.fxpi.chidori.common.receiver.CommonBroadcastReceiver$2.run(Unknown Source)

Please let me know if i need to do anything extra for the release version of apk

**Comment by kvasukib** [comment]
Hi @Sharathnasa,

Thanks for reporting to us. Can you check if the Cognito Identity Pool ID is correct in the release version of the apk? Can you check if the value of the pool ID changes between debug/release version?

**Comment by Sharathnasa** [comment]
@karthikkeyan, Cognito pool Id is same as debug version. I will check
whether it will change when I switch and update you the same.

**Comment by Sharathnasa** [comment]
@kvasukib  no in both the case pool id is same. It's not changing.  Please let me know if you need any further details.

**Comment by Sharathnasa** [comment]
@kvasukib @jpeddicord @fgoncalves @vinu @snkashis This is a issue with cognito sdk. Since i had enterprise support i raised an case. Support team was able to reproduce the issue. It has been assigned to cognito team.

**Comment by kvasukib** [comment]
Thanks, @Sharathnasa for the reply.
