### ISSUE TITLE
Failed to create fire store 

### ISSUE THREAD

**Issue by ashutoshLbbd** [aws/aws-sdk-android#401]
### To help us solve your problem better, please answer the following list of questions.

**I've implemented :** 
String kinesisDirectory = "YOUR_UNIQUE_DIRECTORY";
KinesisRecorder recorder = new KinesisRecorder(
    myActivity.getDir(kinesisDirectory, 0)
    Regions.US_WEST_2,
    credentialsProvider
    );

* What service are you using?   Kinesis

* In what version of SDK are you facing the problem?     2.2.+

* Is the issue limited to Simulators / Actual Devices?    Actual Devices 

* Can your problem be resolved if you bump to a higher version of SDK? Don't Know

* Is this problem related to specific Android/OS version?   Android

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

* Please include a stacktrace if applicable.

**Fatal Exception: com.amazonaws.AmazonClientException
Failed to create fire store**

Fatal Exception: com.amazonaws.AmazonClientException: Failed to create fire store
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FileRecordStore.(Unknown Source)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.KinesisRecorder.(Unknown Source)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.KinesisRecorder.(Unknown Source)

**Caused by java.io.IOException
Read-only file system**

Caused by java.io.IOException: Read-only file system
       at java.io.UnixFileSystem.createFileExclusively0(UnixFileSystem.java)
       at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
       at java.io.File.createNewFile(File.java:948)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FileManager.createDirectory(Unknown Source)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FileRecordStore.tryCreateRecordsFile(Unknown Source)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.FileRecordStore.(Unknown Source)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.KinesisRecorder.(Unknown Source)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.KinesisRecorder.(Unknown Source)

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by rohandubal** [comment]
Hello,

Could you please update to the latest SDK (2.6.15) and please confirm if the issue still persists for you?

Thanks,
Rohan
