### ISSUE TITLE
Unable to marshall request to JSON: java.lang.String[] cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by Sunhick** [aws/aws-sdk-android#409]
* Is this problem related to specific Android/OS version? 
Yes

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Trying to get aws creds for SAML assertion as mentioned in https://docs.aws.amazon.com/cognito/latest/developerguide/saml-identity-provider.html

* Please include a stacktrace if applicable.

Error in getting the aws creds
com.amazonaws.AmazonClientException: Unable to marshall request to JSON: java.lang.String[] cannot be cast to java.lang.String
 at com.amazonaws.services.cognitoidentity.model.transform.GetIdRequestMarshaller.marshall(GetIdRequestMarshaller.java:92)
 at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:435)
 at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
 at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
 at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:658)
 at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:445)
 at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
 at com.test.app.auth.saml.SAML2CognitoProvider.doInBackground(SAML2CognitoProvider.java:62)
 at com.test.app.auth.saml.SAML2CognitoProvider.doInBackground(SAML2CognitoProvider.java:27)
 at android.os.AsyncTask$2.call(AsyncTask.java:304)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 at java.lang.Thread.run(Thread.java:761)

**Comment by kvasukib** [comment]
Thanks you @Sunhick for reporting to us. Sorry for the inconvenience caused. Can you post a code snippet?
