### ISSUE TITLE
Crash in Pinpoint NotificationClient using FCM

### ISSUE THREAD

**Issue by v360** [aws/aws-sdk-android#412]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Pinpoint

* In what version of SDK are you facing the problem?
2.6.15

* Is the issue limited to Simulators / Actual Devices?
Actual Device - 4.1.1

* Can your problem be resolved if you bump to a higher version of SDK?
2.6.15 is the current latest

* Is this problem related to specific Android/OS version?
Yes - seems like this is a known issue with devices before Kitkat (search for stack trace below)

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Send a direct message to a 4.1.1 device after Pinpoint push notification integration (FCM)

* Please include a stacktrace if applicable.
```
java.lang.IllegalArgumentException: Can't use FLAG_RECEIVER_BOOT_UPGRADE here
    at android.os.Parcel.readException(Parcel.java:1429)
    at android.os.Parcel.readException(Parcel.java:1379)
    at android.app.ActivityManagerProxy.getIntentSender(ActivityManagerNative.java:2955)
    at android.app.PendingIntent.getBroadcast(PendingIntent.java:369)
    at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.GCMNotificationClient.createOpenAppPendingIntent(GCMNotificationClient.java:53)
    at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.NotificationClientBase.displayNotification(NotificationClientBase.java:694)
    at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.NotificationClientBase.handleCampaignPush(NotificationClientBase.java:873)
    at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.NotificationClient.handleFCMCampaignPush(NotificationClient.java:174)
    at com.vastra360.V360Creator.firebase.fcm.MyFirebaseMessagingService.a(MyFirebaseMessagingService.java:16)
    at com.google.firebase.messaging.FirebaseMessagingService.b(Unknown Source)
    at com.google.firebase.iid.e.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
    at java.lang.Thread.run(Thread.java:856)
```
If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by v360** [comment]
This crash still exists even with the current latest SDK version 2.6.18:
```
    java.lang.IllegalArgumentException: Can't use FLAG_RECEIVER_BOOT_UPGRADE here
        at android.os.Parcel.readException(Parcel.java:1429)
        at android.os.Parcel.readException(Parcel.java:1379)
        at android.app.ActivityManagerProxy.getIntentSender(ActivityManagerNative.java:2955)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:369)
        at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.GCMNotificationClient.createOpenAppPendingIntent(GCMNotificationClient.java:53)
        at com.amazonaws.mobileconnectors.pinpoint.targeting.notification.NotificationClientBase$1.run(NotificationClientBase.java:700)
        at java.lang.Thread.run(Thread.java:856)
```
