### ISSUE TITLE
App crashing when start

### ISSUE THREAD

**Issue by kopevgale** [aws/aws-sdk-android#413]
i used [https://github.com/aws/aws-sdk-android/]

I start him in real phone, non virtual
android 6 version
my AndroidManifest.xml must contain:
<uses-permission android:name="android.permission.INTERNET"/> <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

where to add add cognito client secret ?
 i have next errors:

`02-20 13:24:17.361 5547-5547/com.amazonaws.cognito.android.samples.authdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                              Process: com.amazonaws.cognito.android.samples.authdemo, PID: 5547
                                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amazonaws.cognito.android.samples.authdemo/com.amazonaws.cognito.android.samples.authdemo.MainActivity}: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthInvalidParameterException: validation failed
                                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2572)
                                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654)
                                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                                  at android.os.Looper.loop(Looper.java:207)
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                                               Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthInvalidParameterException: validation failed
                                                                                                  at com.amazonaws.mobileconnectors.cognitoauth.Auth$Builder.validateCognitoAuthParameters(Auth.java:410)
                                                                                                  at com.amazonaws.mobileconnectors.cognitoauth.Auth$Builder.build(Auth.java:355)
                                                                                                  at com.amazonaws.cognito.android.samples.authdemo.MainActivity.initCognito(MainActivity.java:122)
                                                                                                  at com.amazonaws.cognito.android.samples.authdemo.MainActivity.onCreate(MainActivity.java:48)
                                                                                                  at android.app.Activity.performCreate(Activity.java:6314)
                                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
                                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654) 
                                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                                  at android.os.Looper.loop(Looper.java:207) 
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5728) 
                                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                                               Caused by: com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthInvalidParameterException: {"AppCognitoWebDomain":"invalid"}
                                                                                                  at com.amazonaws.mobileconnectors.cognitoauth.Auth$Builder.validateCognitoAuthParameters(Auth.java:407)
                                                                                                  at com.amazonaws.mobileconnectors.cognitoauth.Auth$Builder.build(Auth.java:355) 
                                                                                                  at com.amazonaws.cognito.android.samples.authdemo.MainActivity.initCognito(MainActivity.java:122) 
                                                                                                  at com.amazonaws.cognito.android.samples.authdemo.MainActivity.onCreate(MainActivity.java:48) 
                                                                                                  at android.app.Activity.performCreate(Activity.java:6314) 
                                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519) 
                                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2654) 
                                                                                                  at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488) 
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                                                  at android.os.Looper.loop(Looper.java:207) 
                                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5728) 
                                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
`

**Comment by kvasukib** [comment]
Hi @kopevgale, Thank you for reporting to us. You need to add the cognito-client-secret in the strings.xml file. Reference: https://github.com/awslabs/aws-sdk-android-samples/blob/master/AmazonCognitoAuthDemo/app/src/main/res/values/strings.xml#L8

**Comment by kopevgale** [comment]
Cognito pool id and cognito client id  is same value?

where in the code example Pool ARN?

**Comment by minbi** [comment]
Hi @kopevgale ,

No. Cognito pool id is not used in this context.

**For the client id:**
Go to the Cognito console, choose `User Pools`.
Choose your app from the grid of apps.
Find the left menu item `App client settings`
Each `App client` will have a "card" that same card will have an `ID` on the second line.

Can you clarify what you need the "values" in the second part of your question for?

**Comment by kopevgale** [comment]
Hi all,
where i take :
<string name="app_redirect">demoapp://www.loginactivity.com/mainactivity</string>

and two next values?

    <string name="app_access_token">access_token</string>
    <string name="app_id_token">id_token</string>

**Comment by kopevgale** [comment]
where can i find access_token id_token amazon?

**Comment by desokroshan** [comment]
@kopevgale 

You don't have need to replace the replace the following resources:
```
<string name="app_access_token">access_token</string>
<string name="app_id_token">id_token</string>
```
You can leave these as is. This issue has a resolution [here](https://github.com/awslabs/aws-sdk-android-samples/issues/161). Please update there if issue still persists. 

Thanks, Roshan

**Comment by chikka** [comment]
validation still failing in line 
`Patterns.DOMAIN_NAME.matcher(uri).matches();`

for validateCognitoAuthParameters method.
