### ISSUE TITLE
Android Pinpoint init loadAttributes error

### ISSUE THREAD

**Issue by v360** [aws/aws-sdk-android#414]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
Pinpoint

* In what version of SDK are you facing the problem?
2.6.15

* Is the issue limited to Simulators / Actual Devices?
Both

* Can your problem be resolved if you bump to a higher version of SDK?
2.6.15 is the current latest

* Is this problem related to specific Android/OS version?
No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
Add a custom attribute as specified in the documentation:
```
pinpointManager.getTargetingClient().addAttribute("phoneNumber", Arrays.asList(new String[]{"+911234567890"}));
pinpointManager.getTargetingClient().updateEndpointProfile();
```
The attribute shows up fine in the endpoint profile:
```
aws --region=us-east-1 --profile=[profile] pinpoint get-endpoint --application-id [appId] --endpoint-id [endpointId]
```

```
.....
        "CohortId": "11", 
        "Attributes": {
            "phoneNumber": [
                "+911234567890"
            ]
        }, 
        "ChannelType": "GCM", 
.....
```
However, when the app initialises Pinpoint, we see that it fails to load the attributes - see stack trace below.

* Please include a stacktrace if applicable.
```
org.json.JSONException: Value [+911234567890] at phoneNumber of type java.lang.String cannot be converted to JSONArray
     at org.json.JSON.typeMismatch(JSON.java:100)
     at org.json.JSONObject.getJSONArray(JSONObject.java:548)
     at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient.loadAttributes(TargetingClient.java:222)
     at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient.<init>(TargetingClient.java:80)
     at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient.<init>(TargetingClient.java:90)
     at com.amazonaws.mobileconnectors.pinpoint.PinpointManager.<init>(PinpointManager.java:108)
     at .....
     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$5$1.run(CognitoUser.java:681)
     at android.os.Handler.handleCallback(Handler.java:615)
     at android.os.Handler.dispatchMessage(Handler.java:92)
     at android.os.Looper.loop(Looper.java:137)
     at android.app.ActivityThread.main(ActivityThread.java:4745)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:511)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
     at dalvik.system.NativeStart.main(Native Method)
```
If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by mohitmahi** [comment]
You are writing below an incorrect code.
pinpointManager.getTargetingClient().addAttribute("phoneNumber", Arrays.asList(new String[]{"+911234567890"}));

Expected one should be:
pinpointManager.getTargetingClient().addAttribute("phoneNumber", new ArrayList<String>(Arrays.asList("+911234567890")));

**Comment by v360** [comment]
Ok, I'll try the new code.

Looks like the documentation is now updated.

The older [version](https://webcache.googleusercontent.com/search?q=cache:CVc-86K8fc8J:https://docs.aws.amazon.com/pinpoint/latest/developerguide/mobile-sdk-android-register.html+&cd=1&hl=en&ct=clnk&gl=in
) mentioned the code I was using:
```
AWSMobileClient.defaultMobileClient()
    .getPinpointManager().getTargetingClient().addAttribute("favoriteTeams", Arrays.asList(new String[]{"Lakers", "Clippers"}));
```

**Comment by v360** [comment]
```
pinpointManager.getTargetingClient().addAttribute("phoneNumber", new ArrayList(Arrays.asList("+911234567890")));
```

didn't work either.

Even code as per the latest documentation:
```
final List<String> phoneNumbers = Arrays.asList("+911234567890", "test");
pinpointManager.getTargetingClient().addAttribute("phoneNumber", phoneNumbers);
```

showed an exception when initialising:
```
03-29 19:37:27.290 1618-1618/com.xxx.yyy W/System.err: org.json.JSONException: Value [+911234567890, test] at phoneNumber of type java.lang.String cannot be converted to JSONArray
        at org.json.JSON.typeMismatch(JSON.java:100)
        at org.json.JSONObject.getJSONArray(JSONObject.java:548)
        at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient.e(TargetingClient.java:228)
        at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient.<init>(TargetingClient.java:81)
        at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient.<init>(TargetingClient.java:91)
        at com.amazonaws.mobileconnectors.pinpoint.PinpointManager.<init>(PinpointManager.java:111)
...
```

**Comment by mohitmahi** [comment]
Try below one. 

pinpointManager.getTargetingClient().addAttribute("phoneNumber", new ArrayList<String>(Arrays.asList("+911234567890")));

**Comment by mohitmahi** [comment]
Try below one.

pinpointManager.getTargetingClient().
addAttribute("phoneNumber", new ArrayList<String>(Arrays.asList("+911234567890")));

**Comment by mohitmahi** [comment]
Some how git is removing generic declaration , after new Arraylist declare generic String
new ArrayList<String>(.....)

**Comment by v360** [comment]
@mohitmahi I didn't follow your last comment.

Please note that my problem is not with adding the custom attribute.  As mentioned in the initial post, the custom attribute gets added fine - it also shows up fine as an array when queried using the AWS CLI (see the initial post).  The stack trace shows up when initialising Pinpoint (after a custom attribute has been added during a previous run)
