### ISSUE TITLE
NullPointerException on publishMessagesFromQueue

### ISSUE THREAD

**Issue by matsujun** [aws/aws-sdk-android#421]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS IoT

* In what version of SDK are you facing the problem?
2.6.15

* Is the issue limited to Simulators / Actual Devices?
Actual Device (Zenfone 3/Android 7.0)

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
We have checked only one device / os version

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

We have no steps.
It sometimes crash in background.

* Please include a stacktrace if applicable.
```
java.lang.NullPointerException: Attempt to read from field 'java.lang.Object java.util.LinkedList$Node.item' on a null object reference
at java.util.LinkedList.unlink(LinkedList.java:211)
at java.util.LinkedList.remove(LinkedList.java:526)
at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.publishMessagesFromQueue(AWSIotMqttManager.java:1190)
at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$5.run(AWSIotMqttManager.java:1222)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:159)
at android.app.ActivityThread.main(ActivityThread.java:6097)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

You are checking `mqttMessageQueue.isEmpty()` before `mqttMessageQueue.remove(0)` , so it may multi threading issue.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html ). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by kvasukib** [comment]
Hi @matsujun, Thank you for reporting to us. Can you share us a code snippet where this issue is reproduced?
