### ISSUE TITLE
AmazonClientException Input stream exceeds 256k buffer

### ISSUE THREAD

**Issue by niqo01** [aws/aws-sdk-android#43]
Using Android Aws sdk 2.2.1 I am seeing a few occurrence of this exception (Only on Android 5.0 and 5.1.1 so far):
```
com.amazonaws.AmazonClientException: Input stream exceeds 256k buffer.
       at com.amazonaws.services.s3.AmazonS3Client.toByteArray(AmazonS3Client.java:4378)
       at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1581)
       at com.amazonaws.mobileconnectors.s3.transfermanager.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:134)
       at com.amazonaws.mobileconnectors.s3.transfermanager.internal.UploadCallable.call(UploadCallable.java:126)
       at com.amazonaws.mobileconnectors.s3.transfermanager.internal.UploadMonitor.upload(UploadMonitor.java:182)
       at com.amazonaws.mobileconnectors.s3.transfermanager.internal.UploadMonitor.call(UploadMonitor.java:140)
       at com.amazonaws.mobileconnectors.s3.transfermanager.internal.UploadMonitor.call(UploadMonitor.java:54)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```
Can you guys clarify what's going on?

**Comment by fosterzhang** [comment]
Would you please show me the code snippet that uploads the file?

It looks like you try to upload an input stream but the content length of it isn't set in ObjectMetadata. Content length is required for upload. The client tries to calculate it by buffering the input stream, only up to 256k to avoid consuming to much memory. You will get an exception if the input stream is too large.

To avoid it, you can either use upload(String, String, File) to upload a file. Or explicit set the content length in ObjectMetadata if you want to upload an input stream.

**Comment by niqo01** [comment]
Thanks for the fast response. here is a code snippet:
```
        Long imageSize =
              fromMediaPick ? PlatformUtils.getSizeFromContentUri(context.getContentResolver(),
                  photoUploadInfo.uri) : 0L;
        if (imageSize == null || imageSize <= 0) {
            Timber.w("Couldn't determine image size");
            imageSize = 0L;
        }
        photoUploadInfo.size = imageSize;
        photoUploadInfo.uri = PlatformUtils.transformPicassaUri(photoUploadInfo.uri);

        InputStream dataStream =
              context.getContentResolver().openInputStream(photoUploadInfo.uri);

        String key = CouchsurfingApiUtils.getAwsKey(userId);
        PutObjectRequest putObjectRequest =
              new PutObjectRequest(awsBucket, key, dataStream, new ObjectMetadata());
....
        putObjectRequest.setCannedAcl(CannedAccessControlList.PublicRead);
        putObjectRequest.getMetadata().setUserMetadata(CouchsurfingApiUtils.getAwsUserMetadata(userId, albumId));
        final Upload upload = awsTransferManager.upload(putObjectRequest);
```
I use to set the content length metadata but I was getting sometimes: 
```
Got AmazonClientException: Data read (1511526) has a different length than the expected (3775456)
```
Removing the content length solved the issue for me. Ill try the file option as you recommend.

**Comment by fosterzhang** [comment]
``` java
PutObjectRequest putObjectRequest =
              new PutObjectRequest(awsBucket, key, dataStream, new ObjectMetadata());
```
The above code uses the default ObjectMetadata which sets content length to be zero. You may be upload without an error, but will actually result in an empty object on S3. Here is what I suggest:
``` java
ObjectMetadata meta = new ObjectMetadata();
// explicitly set the content length here
meta.setContentLength(imageSize);
meta.setUserMetadata(CouchsurfingApiUtils.getAwsUserMetadata(userId, albumId));
PutObjectRequest putObjectRequest =
              new PutObjectRequest(awsBucket, key, dataStream, meta);
final Upload upload = awsTransferManager.upload(putObjectRequest);
```

**Comment by niqo01** [comment]
@fosterzhang I was doing this before and was getting issues similar to:
```
AmazonClientException: Data read (1511526) has a different length than the expected (3775456)
```
Like if the Android content resolver didn't provide the right size.. I think I prefer to go the File road.
Thanks for your help.

**Comment by fosterzhang** [comment]
Awesome. Feel free to reopen this if you have further questions.
