### ISSUE TITLE
 Invalid login token. Issuer doesn't match providerName

### ISSUE THREAD

**Issue by Antpachon** [aws/aws-sdk-android#444]
2.6.18

Hi.  I am trying to associate a logged in user with an identity pool however I keep getting Issuer doesn't match provider name. I have checked the federated identity pool and in the authentication providers I have the user pool where the user has logged in correctly.

Am I missing something?

`        CognitoCredentialsProvider cognitoCredentialsProvider = new CognitoCredentialsProvider(identityPoolId, Region);
Map<String, String> logins = new HashMap<>();
        logins.put("cognito-idp.eu_west_1.amazonaws.com/eu-west-1_xxxxxx", userSession.getIdToken().getJWTToken());
        cognitoCredentialsProvider.setLogins(logins); 
        cognitoCredentialsProvider.refresh();`

`com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Invalid login token. Issuer doesn't match providerName (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 8ba7f78c-3e65-11e8-xxxxxxx)
                                                                       at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:729)
                                                                       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
                                                                       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
                                                                       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:559)
                                                                       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:445)
                                                                       at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
                                                                       at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
                                                                       at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:658)
                                                                       at com.amazonaws.auth.CognitoCredentialsProvider.refresh(CognitoCredentialsProvider.java:611)
                                                                       at com.amazonaws.auth.CognitoCachingCredentialsProvider.refresh(CognitoCachingCredentialsProvider.java:514)
                                                                       at awslib.cirrus.com.awslibrary.AWSManager.onLoginSucces(AWSManager.java:144)
                                                                       at awslib.cirrus.com.awslibrary.AWSManager.access$000(AWSManager.java:44)
                                                                       at awslib.cirrus.com.awslibrary.AWSManager$1.onSuccess(AWSManager.java:114)
                                                                       at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$27.run(CognitoUser.java:2441)
                                                                       at awslib.cirrus.com.awslibrary.AWSManager.lambda$login$0$AWSManager(AWSManager.java:136)
                                                                       at awslib.cirrus.com.awslibrary.AWSManager$$Lambda$0.run(Unknown Source:0)`

**Comment by Antpachon** [comment]
Hi @kvasukib, I tried that already and no luck.  (See my original message)

`logins.put("cognito-idp.eu_west_1.amazonaws.com/eu-west-1_xxxxxx", userSession.getIdToken().getJWTToken());`

After doing that and calling refresh() or trying to use the credentials , I get the invalid token error. The user is authenticated correctly. The user pool id is an auth provider in the identity pool. The identity pool id I am using is the right one, not sure what else can I try.

**Comment by kvasukib** [comment]
@Antpachon can you check the code once again? The region name is the key should be` eu-west-1` whereas you are using `eu_west_1`. Can you replace the underscore by hyphen and try again?

**Comment by Antpachon** [comment]
That was the issue... T_T thanks!

**Comment by akmustafa** [comment]
It helps me to learn the ProviderName format for CognitoAWSCredentials.
Thank You

`cognito-idp.eu-west-1.amazonaws.com/eu-west-1_xxxxxx`
