### ISSUE TITLE
Mulit-part upload fails with transfer acceleration in 2.6.+

### ISSUE THREAD

**Issue by rr0055256** [aws/aws-sdk-android#473]
Facing issue when we have transfer acceleration enabled on the S3 client object with Amazon AWS Android SDK 2.6+. However, the transfer acceleration works with 2.2+.

Below are the details -
1. The version of SDK used - 2.6+
2. The issue was detected in the actual device - Android 6.0.0
3. Problem is solved with a lower version of the SDK (2.2.+)
4. The issue is not related to Android OS version. Looks to be generic
5. PFB the details of the code - 
S3 client object in kotlin -
Note - Have not shared the actual access key, secret key, and the bucket name.

```
    val basicAWSCredentials = BasicAWSCredentials("ACCESS KEY","SECRET KEY")
            sS3Client = AmazonS3Client(basicAWSCredentials)
            sS3Client?.setRegion(Region.getRegion(Regions.US_EAST_1))
                        sS3Client?.setS3ClientOptions(S3ClientOptions.builder().setAccelerateModeEnabled(true).build())
            sS3Client?.setBucketAccelerateConfiguration("BUCKET NAME", BucketAccelerateConfiguration(
                    BucketAccelerateStatus.Enabled))
```

PFB the trace logs-
```
06-06 12:56:20.253 22241-23532/app.android.reeltime E/UploadTask: Error initiating multipart upload: 15 due to Unable to execute HTTP request: Unable to resolve host "s3-accelerate.amazonaws.com": No address associated with hostname
    com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "s3-accelerate.amazonaws.com": No address associated with hostname
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4654)
        at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3485)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.initiateMultipartUpload(UploadTask.java:269)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:102)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:82)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.UnknownHostException: Unable to resolve host "s3-accelerate.amazonaws.com": No address associated with hostname
        at java.net.InetAddress.lookupHostByName(InetAddress.java:440)
        at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
        at java.net.InetAddress.getAllByName(InetAddress.java:215)
        at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
        at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:357)
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
        at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
        at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4654) 
        at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3485) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.initiateMultipartUpload(UploadTask.java:269) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:102) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:82) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:46) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

Please let me know, if you need more details.

**Comment by kvasukib** [comment]
Thank you @rr0055256 for reporting to us. Sorry for the inconvenience caused.  I wrote a test with the code sample you posted and the transfer went through successfully. Do you have transfer acceleration enabled on the bucket in the S3 console?

The endpoint should be <bucket-name>.s3-accelerate.amazonaws.com however in your stack trace, I don't see the bucket-name in the hostname. 
Does this error happen for transfers without transfer acceleration? 
Among the transfers with transfer acceleration, what percent of transfers encounter this error?

**Comment by rr0055256** [comment]
Thanks for your response. Yes, transfer acceleration is enabled on the bucket. Yes, you are right, once you enable the transfer acceleration on the bucket, it points to <bucket-name>.s3-accelerate.amazonaws.com. However, the sdk code, does not allow me to set the end point manually as its says, I only have to enable transfer acceleration method. I'm able to upload without transfer acceleration enabled  and percentage of failure is 0%. The weird part is it works with transfer acceleration on the downgraded Amazon AWS SDK. Please let me know, if you need further details.

**Comment by kvasukib** [comment]
Hi @rr0055256, Thank you for the detailed response. I tried the following:

 public AmazonS3Client getS3Client(Context context) {
        final CountDownLatch countDownLatch = new CountDownLatch(1);

        if (sS3Client == null) {
            BasicAWSCredentials credentials = new BasicAWSCredentials(key, secret);
            sS3Client = new AmazonS3Client(credentials);
            sS3Client.setRegion(Region.getRegion(Regions.AP_SOUTHEAST_1));                                                 sS3Client.setS3ClientOptions(S3ClientOptions.builder().setAccelerateModeEnabled(true).build());

           // wrap the call in a thread since we make a network call.
            new Thread(new Runnable() {
                @Override
                public void run() {
                    sS3Client.setBucketAccelerateConfiguration(Constants.BUCKET_NAME,
                            new BucketAccelerateConfiguration(BucketAccelerateStatus.Enabled));
                    countDownLatch.countDown();
                }
            }).start();
        }

        try {
            countDownLatch.await();
        } catch (InterruptedException ie) {
            ie.printStackTrace();
        }

        return sS3Client;
    }

I created a new bucket without transfer acceleration. After this function gets executed,  I am able to see the transfer acceleration being enabled on the console and the endpoint is set correctly.

After this I tried uploading a file of 100MB: The request constructed is as follows:

POST https://mybucket.s3-accelerate.amazonaws.com /file_100mb.mp4 Parameters: (uploads: null, ) Headers: (Content-Type: video/mp4, x-amz-acl: public-read, Content-Length: 0, ) 

Can I know your bucket name? Does it have '/' in it? or any Unicode characters? (See Bucket Naming: https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html)

**Comment by rr0055256** [comment]
Thanks. Solved my problem. The issue was , I had already enabled transfer acceleration on the bucket. Disabling the transfer acceleration in the bucket and then enabling via the function from the code solved the problem.

**Comment by kvasukib** [comment]
Thank you @rr0055256 for confirming. I have added few tests in TransferUtility on transfer acceleration.
