### ISSUE TITLE
S3 SDK impacting more than 10% of users with 2 major crashes

### ISSUE THREAD

**Issue by appndigital** [aws/aws-sdk-android#475]
###

* What service are you using?
S3 and cognito

* In what version of SDK are you facing the problem?
2.6.+

* Is the issue limited to Simulators / Actual Devices?
ActualDevices

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
Only Android

###

We have 2 majors crashes on our app related to Amazon S3.

1. URLHttpClient.java - Unable to resolve host
This one appers two times : 
One with "cognito-identity.eu-west-1.amazonaws.com"
The other one with {our bucket}.s3.amazonaws.com

2. XmlResponsesSaxParser.java - Unable to execute HTTP request: timeout

Can you help us find a way to prevent theses issues ?

**Comment by kvasukib** [comment]
Thank you @appndigital for reporting to us. Sorry for the inconvenience caused. 
Can you post a stack trace and a sample code snippet? 
Can you check if there are intermittent network connectivity issues?
What is the frequency of this issue? For every file, type, and size? 
Does this occur on certain devices or Android versions?

**Comment by appndigital** [comment]
Hi @kvasukib 
Here is a code snippet

`TransferUtility transferUtility = new TransferUtility(s3, this);

            final TransferObserver observer = transferUtility.upload(
                    Utils.AWS_BUCKET,     /* The bucket to upload to */
                    title,    /* The key for the uploaded object */
                    fileToUpload        /* The file where the data to upload exists */
            );

            observer.setTransferListener(new TransferListener() {
                @Override
                public void onStateChanged(int id, TransferState state) {
                    if (state.equals(TransferState.COMPLETED)) {
                        //Success
                        count--;
                        updatePercentage();

                    }
                }

                @Override
                public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                }

                @Override
                public void onError(int id, Exception ex) {
                    countError++;
                }
            });`


and the trace

> Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:330)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:776)

> Caused by com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.eu-west-1.amazonaws.com": No address associated with hostname
       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:563)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:389)
       at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:747)
       at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:673)
       at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:444)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4648)
       at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:5406)
       at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:5381)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4645)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4602)
       at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:672)
       at com.photoweb.piiics.utils.AWSHandler$DownloadFolderClass$DownloadFolderTask.doInBackground(AWSHandler.java:117)
       at com.photoweb.piiics.utils.AWSHandler$DownloadFolderClass$DownloadFolderTask.doInBackground(AWSHandler.java:112)
       at android.os.AsyncTask$2.call(AsyncTask.java:316)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:776)

**Comment by appndigital** [comment]
It happens on various brands of phones and version of Android.

**Comment by kvasukib** [comment]
Thank you @appndigital for the quick reply. I see that you are getting an exception when you are trying to list object through the AmazonS3Client. Can you post a code snippet of how you are constructing the AmazonS3Client object, transfer utility object and the call to listObjects?

**Comment by edward-sentongo** [comment]
Running the sample app (https://docs.aws.amazon.com/aws-mobile/latest/developerguide/getting-started.html#add-aws-mobile-sdk-connect-to-your-backend) produces the same error:

_"Unable to execute HTTP request: Unable to resolve host "cognito-identity.eu-west-1.amazonaws.com": No address associated with hostname"_

**Comment by gurpreetwegile** [comment]
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "s3.amazonaws.com": No address associated with hostname
