### ISSUE TITLE
When change to V2 Signature, Upload failed when files bigger then 5MB

### ISSUE THREAD

**Issue by wuseal** [aws/aws-sdk-android#497]
Hi, When setting this 
```java
        ClientConfiguration opts = new ClientConfiguration();
        opts.setSignerOverride("S3SignerType");  // NOT "AWS3SignerType"
        AmazonS3Client s3 = new AmazonS3Client(getCredProvider(context.getApplicationContext()),opts);
```
standard endpoint, It will work ok when upload file below 5 MB ,and when upload file bigger then 5MB .It will throw an exception like this:
```log
com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: AFBCE47F09747899), S3 Extended Request ID: b2LJLc/1GjyflgfrUk90XdPjEZIKUR8EYt8EGHvP/qeBWDXpZAH9atPR2UGb6i/kw+y2wxz1NHI=
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4654)
        at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:3485)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.initiateMultipartUpload(UploadTask.java:270)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadMultipartAndWaitForCompletion(UploadTask.java:103)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:83)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:47)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```
Help! Is there anything i missed? 

SDK version:2.6.19
Real Device Environment

**Comment by wuseal** [comment]
@minbi Thank you for your reply，Our business have been using version 2 signature from six years ago, now we want to upgrade to use android sdk, the default signature is v4 in the newest version sdk, all works ok but when we generate a presigned url with expiration longger than 7 days it throw out an exception says that expiration only can be 7 days at most, but our app need the presigned url Validity period at least 20 years for current code logic. For keep compatible with pre code logic I find the solution on the internet is change to use v2 signature.

but exception is throw out when upload files bigger than 5 MB.

**Comment by wuseal** [comment]
@minbi Hi, this is the code that I set the region to  us-west-2
```java
 private static CognitoCachingCredentialsProvider getCredProvider(Context context) {
        if (sCredProvider == null) {
            synchronized (CognitoCachingCredentialsProvider.class) {
                if (sCredProvider == null) {
                    sCredProvider = new CognitoCachingCredentialsProvider(
                            context.getApplicationContext(),
                            S3Consts.COGNITO_POOL_ID,
                            Regions.US_WEST_2);
                }
            }
        }
        return sCredProvider;
    }
```
Am I setting right? if it's ok,should it do work?

**Comment by wuseal** [comment]
@minbi I am puzzled, why uploading file smaller than 5MB can be successful, uploading more than 5MB will report the signature mismatch error?

**Comment by wuseal** [comment]
@kvasukib So? Multi-part upload throw out he signature mismatch exception?

**Comment by wuseal** [comment]
@kvasukib Ok, I'll use the V4 signature to upload files. thanks for your reply
