### ISSUE TITLE
Can't upload file over Airtel 3G connection

### ISSUE THREAD

**Issue by miketrewartha** [aws/aws-sdk-android#498]
* **What service are you using?**
`com.amazonaws:aws-android-sdk-s3:2.6.25`

* **In what version of SDK are you facing the problem?**
2.6.25

* **Is the issue limited to Simulators / Actual Devices?**
Unsure about emulator, definitely exists on real device (Nokia 6.1)

* **Can your problem be resolved if you bump to a higher version of SDK?**
No, I'm on the most recent version

* **Is this problem related to specific Android/OS version?**
Unsure, I can only test on Android 8.1.0 devices at the moment (traveling in Africa, don't have access to other devices)

* **Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.**
All I'm doing is uploading a small (1-4 kB) file to an S3 bucket via a pre-signed URL. I'm parsing apart the URL to get the bucket, path, etc... and I've verified everything is parsed apart correctly. The issue doesn't occur when the device is connected to WiFi, but occurs every time when uploading over my Airtel 3G connection. I've verified the 3G connection is fine by connecting to various other websites, downloading a public file (via the browser, not my app) from my bucket, etc... I've also tried uploading the file manually via a PUT to the URL and get the same results (works on WiFi, doesn't work on Airtel 3G).

* **Please include a stacktrace if applicable.**
```
com.amazonaws.AmazonClientException: Encountered an exception and couldn't reset the stream to retry
        at com.amazonaws.http.AmazonHttpClient.resetRequestAfterError(AmazonHttpClient.java:511)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:452)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752)
        ...
Caused by: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x77e4511c08: I/O error during system call, Connection reset by peer
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@12685023@12.6.85 (040400-197041431):3)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@12685023@12.6.85 (040400-197041431):19)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
        at com.google.firebase.perf.network.zze.getOutputStream(Unknown Source:4)
        at com.google.firebase.perf.network.zzd.getOutputStream(Unknown Source:2)
        at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
        at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659) 
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752)
        ...
```

**Comment by miketrewartha** [comment]
I'm using an `AmazonS3Client`, like so:

```kotlin
val cognitoCredentialsProvider = CognitoCachingCredentialsProvider(
        context,
        "my-identity-pool-id",
        Regions.US_EAST_1,
        ClientConfiguration()
)
val amazonS3Client = AmazonS3Client(cognitoCredentialsProvider)
val bucket = "my_bucket"
val key = "my/key"
val input = anInputStream
val metadata = ObjectMetadata().apply {
        contentLength = input.available().toLong()
}
amazonS3Client.putObject(PutObjectRequest(bucket, key, input, metadata))
```

This project is closed source, so I changed one line to just show `com.example.Repo`, but it's identical otherwise:

```
com.amazonaws.AmazonClientException: Encountered an exception and couldn't reset the stream to retry
        at com.amazonaws.http.AmazonHttpClient.resetRequestAfterError(AmazonHttpClient.java:511)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:452)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752)
        at com.parsyl.repos.remote.DefaultRemoteRawDataRepo$uploadRawData$1$1.run(DefaultRemoteRawDataRepo.kt:32)
        at io.reactivex.internal.operators.completable.CompletableFromRunnable.subscribeActual(CompletableFromRunnable.java:35)
        at io.reactivex.Completable.subscribe(Completable.java:1918)
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:111)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
        at retrofit2.adapter.rxjava2.CallEnqueueObservable$CallCallback.onResponse(CallEnqueueObservable.java:62)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:123)
        at com.google.firebase.perf.network.zzg.onResponse(Unknown Source:16)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x71e8ff5c88: I/O error during system call, Connection reset by peer
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@12685023@12.6.85 (040400-197041431):3)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@12685023@12.6.85 (040400-197041431):19)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
        at com.google.firebase.perf.network.zze.getOutputStream(Unknown Source:4)
        at com.google.firebase.perf.network.zzd.getOutputStream(Unknown Source:2)
        at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
        at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659) 
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752) 
        at com.example.Repo$uploadData$1$1.run(Repo.kt:32) 
        at io.reactivex.internal.operators.completable.CompletableFromRunnable.subscribeActual(CompletableFromRunnable.java:35) 
        at io.reactivex.Completable.subscribe(Completable.java:1918) 
        at io.reactivex.internal.operators.single.SingleFlatMapCompletable$FlatMapCompletableObserver.onSuccess(SingleFlatMapCompletable.java:91) 
        at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:111) 
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66) 
        at retrofit2.adapter.rxjava2.CallEnqueueObservable$CallCallback.onResponse(CallEnqueueObservable.java:62) 
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:123) 
        at com.google.firebase.perf.network.zzg.onResponse(Unknown Source:16) 
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153) 
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)
```

I've also tried a pre-signed URL and get a nearly identical result- the connection never gets established because of an SSL issue. For some reason, this doesn't happen on WiFi and only seems to happen on the Airtel network, although I'm going to try using the other major network here, MTN, tomorrow. It seems like an SSL issue, but I don't do anything out of the ordinary there...

Have you guys ever heard of SSL issues between AWS and carriers?

**Comment by miketrewartha** [comment]
So here's an interesting, seemingly related tidbit. If I use the `AP_SOUTH_1` region like below, the issue goes away and I instead get an API error complaining about the URL I used. That's expected (given the bucket isn't in the `AP_SOUTH_1` region) and indicates the issue isn't actually an SSL issue, but rather an issue with region... Maybe Airtel is refusing to connect to the `US_EAST_1` region for some reason?

```kotlin
val amazonS3Client = AmazonS3Client(cognitoCredentialsProvider).apply {
        setRegion(Region.getRegion(Regions.AP_SOUTH_1))
}
```

**Comment by kvasukib** [comment]
@miketrewartha Thank you for posting the analysis. Can you try other regions to see if you face the same issue? The default region SDK uses is us-east-1 but you can always override it by `setRegion(Region.getRegion(Regions.MY_PREFERRD_REGION))`.

**Comment by miketrewartha** [comment]
We've decided to deal with this by delegating the upload to an API endpoint of our own (which I have no trouble accessing over Airtel). This was a frustrating problem to find though, so I'd like to get it fixed for others. I'll get to trying the other regions sometime in the next few days.

**Comment by kvasukib** [comment]
Thank you! Let us know how the testing goes.
