### ISSUE TITLE
Crash aws-sdk-android-mobileanalytics 2.2.2 eventClient.submitEvents()

### ISSUE THREAD

**Issue by GMuniz** [aws/aws-sdk-android#50]
Hi,

I've been trying to integrate my application with AWS Analytics, I was able to successfully authenticate with cognito, and also get an instance of the `MobileAnalyticsManager`... BUT when my activity pauses, and eventClient attempts to submitEvents... my application crashes.

The stacktrace I'm getting, but I'm not quite sure if it's related... it's the following:

> 07-01 16:39:59.177  23841-27327/? I/AmazonHttpClient﹕ Unable to execute HTTP request: null
    java.io.EOFException
            at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95)
            at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:175)
            at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
            at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:616)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:379)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseMessage(HttpURLConnectionImpl.java:487)
            at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseMessage(DelegatingHttpsURLConnection.java:109)
            at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseMessage(HttpsURLConnectionImpl.java:25)
            at com.amazonaws.http.UrlHttpClient.createHttpResponse(UrlHttpClient.java:72)
            at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:66)
            at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
            at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
            at com.amazonaws.services.mobileanalytics.AmazonMobileAnalyticsClient.invoke(AmazonMobileAnalyticsClient.java:335)
            at com.amazonaws.services.mobileanalytics.AmazonMobileAnalyticsClient.putEvents(AmazonMobileAnalyticsClient.java:275)
            at com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.delivery.DefaultDeliveryClient.submitEvents(DefaultDeliveryClient.java:317)
            at com.amazonaws.mobileconnectors.amazonmobileanalytics.internal.delivery.DefaultDeliveryClient$3.run(DefaultDeliveryClient.java:282)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

How can I get this solved ?

Thanks! 

EDIT: This was issued while running an AVD with API 21, haven't tried on a real device.

**Comment by fosterzhang** [comment]
Are you running the AVD behind an Http proxy, like Charles?

**Comment by GMuniz** [comment]
Nope

**Comment by fosterzhang** [comment]
Sorry for the late reply. I can't reproduce this problem. Can you provide a code snippet to reproduce it reliably?

**Comment by fosterzhang** [comment]
This issue is closed due to lack of information to reproduce the problem. Feel free to reopen it.
