### ISSUE TITLE
Still getting crash with S3

### ISSUE THREAD

**Issue by appndigital** [aws/aws-sdk-android#503]
Hello, 

sorry for the late answer but we still got crash with S3.

We still got issue at download (same I posted previously) and I confirm that the Internet Permission is set.

Here is how we construct the client: 

```
CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                getApplicationContext(),   
                Utils.AWS_POOL,   
                Utils.AWS_REGION   
        );

        s3 = new AmazonS3Client(credentialsProvider);

public class DownloadFolderTask extends AsyncTask<ListObjectsRequest, Void, Void> {
            @Override
            protected Void doInBackground(ListObjectsRequest... listObjectsRequests) {
                try
                {
                    ListObjectsRequest listObjectsRequest = listObjectsRequests[0];

                    ObjectListing objectListing = s3.listObjects(listObjectsRequest);
                    for (S3ObjectSummary object : objectListing.getObjectSummaries()) {
                        System.out.println(object.getKey());
                        if (object.getKey().toLowerCase().endsWith(".png") || object.getKey().toLowerCase().endsWith(".jpg")) {
                            downloadFileWith(object.getKey());
                        }
                    }
                }catch (AmazonServiceException e) {
                    System.err.println(e.getErrorMessage());
                    System.exit(1);
                }

                return null;
            }

            @Override
            protected void onPostExecute(Void aVoid) {

                
            }
        }
    }

    public void downloadFileWith(final String key) {
        String[] directories = key.split("/");

        File productdir = getApplicationContext().getDir(directories[0], Context.MODE_PRIVATE);
        File mydir = new File(productdir, directories[1]);

        if (!mydir.exists()) {
            mydir.mkdir();
        }

        File downloadfile = new File(mydir, directories[2]);

        final String usedKey = newkey;

        if (!downloadfile.exists()) {
            TransferUtility transferUtility = new TransferUtility(s3, getApplicationContext());

            TransferObserver observer = transferUtility.download(
                    Utils.AWS_BUCKET,     /* The bucket to download from */
                    usedKey,    /* The key for the object to download */
                    downloadfile        /* The file to download the object to */
            );

            observer.setTransferListener(new TransferListener() {
                @Override
                public void onStateChanged(int id, TransferState state) {

                }

                @Override
                public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {

                }

                @Override
                public void onError(int id, Exception ex) {
                    Log.d(TAG, ex.getLocalizedMessage() + " - " + usedKey);
                }
            });
        }


    }
```

Thanks

**Comment by kvasukib** [comment]
Thank you @appndigital for reporting to us. Sorry for the inconvenience caused. 

1) Can you post the exception message and the complete stack trace? 
2) What version of SDK and Android API Level are you using?

**Comment by appndigital** [comment]
Hello, we are using API Level 27 and using sdk version 2.6.18 for S3

Here is the stack trace:

```
Caused by java.net.UnknownHostException: Unable to resolve host "cognito-identity.eu-west-1.amazonaws.com": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:95)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
       at java.net.InetAddress.getAllByName(InetAddress.java:757)
       at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
       at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
       at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:372)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:355)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:273)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:474)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
       at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
       at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:563)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:389)
       at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:747)
       at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:673)
       at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:444)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4648)
       at com.amazonaws.services.s3.AmazonS3Client.getBucketRegionViaHeadRequest(AmazonS3Client.java:5406)
       at com.amazonaws.services.s3.AmazonS3Client.fetchRegionFromCache(AmazonS3Client.java:5381)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4645)
       at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4602)
       at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:672)
       at com.photoweb.piiics.utils.AWSHandler$DownloadFolderClass$DownloadFolderTask.doInBackground(AWSHandler.java:125)
       at com.photoweb.piiics.utils.AWSHandler$DownloadFolderClass$DownloadFolderTask.doInBackground(AWSHandler.java:118)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by kvasukib** [comment]
Thank you @appndigital for posting the code snippet. What is the frequency of this issue? Does this happen for every API call with S3?

**Comment by appndigital** [comment]
Hi,

No it doesn't happen all the time but we get a lot of our users that are facing this issue (1 out of 10)
This is annoying since we'd like to aim 95% of crash free users

**Comment by cbommas** [comment]
@appndigital 

We have seen this error on our side intermittently. In pretty much every case, this has been due a device or simulator getting into a bad network state ( i.e., device dropped off network, device transitioned networks etc) and not related to any availability issue with the cognito service. It is fairly likely that is what is happening in your case as well.

From the code you posted and looking at the stacktrace, looks like this is happening when you are making the  `s3.listObjects` call. This call is surrounded by a try - catch and you are catching the exception, which is great. One suggestion I'd make here would be to catch `AmazonClientException` instead of `AmazonServiceException`

However, I am confused by what you are doing in the ExceptionHandler. 

               catch (AmazonServiceException e) {
                    System.err.println(e.getErrorMessage());
                    System.exit(1);
                }

The `System.exit(1)` here is going to cause the process to exit which will appear to the customer as an app crash. I would suggest you handle this differently  - ( some ideas I can think of are display an error message, doing a retry, check if the device is on the network etc..)

**Comment by kvasukib** [comment]
Apologies for the delay.

We have made some changes to TransferUtility in 2.7.0 version of the SDK. The summary of the changes can be found in [CHANGELOG](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md) or [Documentation](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/how-to-transfer-files-with-transfer-utility.html#long-running-transfers).

Summary:

Starting version 2.7.0 of the SDK, TransferService logic has been refactored. This service now will be responsible only for monitoring network connectivity changes. When the network goes offline, the transfers that are in progress will be paused. When the network comes back online, the transfers that are paused will be resumed. If you expect your app to perform long-running transfers in the background, you need to initiate the transfers from a background service of your choice.

The TransferService will not be started or stopped by TransferUtility anymore. You have to start TransferService manually from your application. A recommended way is to start the service upon Application startup. One way you can do this is to include the following line in the onCreate method of your app's Application class.

```java
    getApplicationContext().startService(new Intent(getApplicationContext(), TransferService.class));
```
