### ISSUE TITLE
Unable to execute HTTP request: Chain validation failed

### ISSUE THREAD

**Issue by wuseal** [aws/aws-sdk-android#509]
Hello, I got this error when on device Pixel 
Android OS: 8.0.0
aws-sdk-android version :2.6.19
```Gradle
implementation 'com.amazonaws:aws-android-sdk-core:2.6.19'
implementation 'com.amazonaws:aws-android-sdk-s3:2.6.19'
implementation 'com.amazonaws:aws-android-sdk-ddb:2.6.19'
```
On other devices ,All run well exception on Pixel, Is there anything wrong with Device or about the System version?
```java
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: me.dingtone.s3library.test, PID: 30448
                  com.amazonaws.AmazonClientException: Unable to execute HTTP request: Chain validation failed
                      at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
                      at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
                      at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4654)
                      at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1747)
                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:214)
                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:88)
                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:47)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                      at java.lang.Thread.run(Thread.java:764)
                   Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
                      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:355)
                      at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
                      at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
                      at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
                      at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
                      at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                      at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
                      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
                      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
                      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source:0)
                      at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
                      at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
                      at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
                      at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
                      at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4654) 
                      at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1747) 
                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:214) 
                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:88) 
                      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:47) 
                      at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                      at java.lang.Thread.run(Thread.java:764) 
                   Caused by: java.security.cert.CertificateException: Chain validation failed
                      at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:705)
                      at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:537)
                      at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:558)
                      at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:603)
                      at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:603)
                      at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:626)
                      at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:493)
                      at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:416)
                      at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:337)
                      at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
                      at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
                      at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:203)
                      at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:592)
E/AndroidRuntime:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:351)
                      	... 26 more
                   Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
                      at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:133)
                      at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:225)
                      at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:143)
                      at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
                      at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
                      at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:701)
                      	... 40 more
                   Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
                      at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:619)
                      at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
                      at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
                      at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
                      at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
                      	... 45 more
                  	Suppressed: java.security.cert.CertPathValidatorException: Could not determine revocation status
                      at sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1092)
                      at sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:910)
                      at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:577)
                      at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
                      at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
                      		... 47 more
```

**Comment by rohandubal** [comment]
Hello @wuseal 

Sorry that you are facing issues while using the SDK.

Could you confirm if this device is in the same network as other devices? The stack trace points at some issue with SSL handshake. 

Thanks,
Rohan

**Comment by wuseal** [comment]
This error has been not happened anymore for a long time, So I close this issue. Thanks.
