### ISSUE TITLE
Fatal Exception: java.lang.NoClassDefFoundError in PinpointManager

### ISSUE THREAD

**Issue by snasrudeen** [aws/aws-sdk-android#553]
**Bug**
Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Lorg/apache/commons/logging/LogFactory;

```
Caused by java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.logging.LogFactory" on path: DexPathList[[zip file "/data/app/com.app-XtLfzgnjKwlNfzo9As7l_w==/base.apk"],nativeLibraryDirectories=[/data/app/com.app-XtLfzgnjKwlNfzo9As7l_w==/lib/arm64, /system/lib64, /vendor/lib64]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at com.amazonaws.mobileconnectors.pinpoint.PinpointManager.<clinit>(PinpointManager.java:53)
       at com.app.activity.BaseActivity.lambda$onCreate$0(BaseActivity.java:176)
       at com.app.activity.-$$Lambda$BaseActivity$2z6VAdtjTXW3MRWnK72oVzRT4aI.onComplete(Unknown Source:2)
       at com.amazonaws.mobile.client.AWSMobileClient$2.onComplete(AWSMobileClient.java:164)
       at com.amazonaws.mobile.auth.core.IdentityManager$4.run(IdentityManager.java:635)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Affecting**
LogFactory in PinpointManager

**Environment**
 minSdkVersion 17
compileSdkVersion 28
targetSdkVersion 28
supportLibrary version 28.0.0

**Device Information**
Device
Brand: Google
Model: Pixel
Orientation: Portrait
RAM free: 2.27 GB
Disk free: 1.4 GB

**Operating System**
Version: 9
Orientation: Portrait
Rooted: No

**Additional context**
Its working fine with the following environment on the same device.

minSdkVersion 17
compileSdkVersion 27
targetSdkVersion 27
supportLibrary version 27.1.1

Crash only happen in 28.

**Comment by kvasukib** [comment]
@snasrudeen What version of SDK are you using? This issue has been fixed in `2.6.30`. Please upgrade to `2.6.30` or later.

**Comment by snasrudeen** [comment]
I was using 2.6.27. Now its working fine with 2.7.6. Thanks for the support.

**Comment by kvasukib** [comment]
@snasrudeen Can you tell us how did you land up in using the `2.6.27` version? We updated our sample apps and documentation to use `2.7.+`, so we are wondering if we missed updating any of our docs to onboard with `2.7.+`?

**Comment by snasrudeen** [comment]
No wrong with the documentation. There was some internal miscommunication. Anyway thank you.

**Comment by muellerfr** [comment]
@snasrudeen, thanks for letting us know.
