### ISSUE TITLE
Error in multi-part upload when uploading a file to S3

### ISSUE THREAD

**Issue by takn** [aws/aws-sdk-android#555]
I am getting a failed to connect to cognito-identity error when trying to put an object in a public S3 bucket.
Right now I would like to anonymously put objects into a public bucket.
I have setup a cognito user pool which allows for unauthed roles. 
The S3 bucket is public. 

**Which AWS Services are you utilizing?**
S3

**Provide code snippets (if applicable)**
This is how i'm setting up my client:

```
AWSMobileClient.getInstance().initialize(activity, awsStartupResult ->

                transferUtility = TransferUtility.builder()
                        .context(activity.getApplicationContext())
                        .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
                        .s3Client(new AmazonS3Client(credentialsProvider))
                        .build()).execute();
```

**Environment(please complete the following information):**
 - SDK Version: 2.7.+

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

```
10-23 15:48:32.542 15384-15574/com.simplesleeplab.sslstore E/UploadTask: Error encountered during multi-part upload: 4 due to Unable to execute HTTP request: failed to connect to cognito-identity.us-east-1.amazonaws.com/35.170.86.102 (port 443) after 2000ms
    com.amazonaws.AmazonClientException: Unable to execute HTTP request: failed to connect to cognito-identity.us-east-1.amazonaws.com/35.170.86.102 (port 443) after 2000ms
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566)
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:448)
        at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
        at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:678)
        at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4653)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:221)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:99)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:55)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.SocketTimeoutException: failed to connect to cognito-identity.us-east-1.amazonaws.com/35.170.86.102 (port 443) after 2000ms
        at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
        at libcore.io.IoBridge.connect(IoBridge.java:122)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
        at java.net.Socket.connect(Socket.java:884)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
        at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:434)
        at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:178)
        at com.android.okhttp.Connection.connect(Connection.java:1322)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:466)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:447)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:353)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:118)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:249)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
        at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
        at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) 
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566) 
        at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:448) 
        at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172) 
        at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76) 
        at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:678) 
        at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465) 
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485) 
        at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77) 
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4653) 
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:221) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:99) 
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:55) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

**Comment by kvasukib** [comment]
@takn Sorry for the inconvenience caused. I see that you are using 2.7.+ version of the SDK. We made changes to the TransferService starting 2.7 version of the SDK where you need to start the transfer service from your app manually. 

Questions:
1) Did they network go offline when the transfer is in progress?

**Comment by takn** [comment]
Thanks for the quick response. I'll give that a try

**Comment by takn** [comment]
Thanks that worked. But now i'm running into a different problem that's kind of unrelated.
When I attempt to put a file into the bucket i get the error below because the file gets written to very often (it's kind of like a log file)
Would you have any advice on how i could 'stream' a file up to the bucket?
The basic use case is to write a set of log files to S3.

```
10-24 12:43:58.100 25368-25942/com.simplesleeplab.sslstore E/UploadTask: Error encountered during multi-part upload: 2584 due to More data read (9014) than expected (8794)
    com.amazonaws.AmazonClientException: More data read (9014) than expected (8794)
        at com.amazonaws.util.LengthCheckInputStream.checkLength(LengthCheckInputStream.java:135)
        at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:101)
        at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:73)
        at com.amazonaws.event.ProgressReportingInputStream.read(ProgressReportingInputStream.java:132)
        at com.amazonaws.auth.AwsChunkedEncodingInputStream.setUpNextChunk(AwsChunkedEncodingInputStream.java:319)
        at com.amazonaws.auth.AwsChunkedEncodingInputStream.read(AwsChunkedEncodingInputStream.java:173)
        at java.io.InputStream.read(InputStream.java:162)
        at com.amazonaws.http.UrlHttpClient.write(UrlHttpClient.java:244)
        at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:171)
        at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659)
        at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:221)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:99)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:55)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

```

**Comment by kvasukib** [comment]
@takn Sorry for the delayed response. The AWS Android SDK for S3 does not support streaming content to your S3 bucket. However, you can use Kinesis Streams to stream content to your bucket. 
See https://docs.aws.amazon.com/streams/latest/dev/amazon-kinesis-streams.html to learn about Kinesis Streams.

You can take a look at our SDK for Kinesis: https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-kinesis/src/main/java/com/amazonaws/mobileconnectors/kinesis/kinesisrecorder/KinesisRecorder.java The tests also showcase how to use the API.

**Comment by takn** [comment]
Thank you. Feel free to close this now. no further questions.
