### ISSUE TITLE
AmazonClientException crashes app on bad network

### ISSUE THREAD

**Issue by NightOwlCoder** [aws/aws-sdk-android#556]
Hey there,
using com.amazonaws:aws-android-sdk-iot:2.7.6 to connect to my service, is crashing my app.

Full stack is below, but basically I see that this call:

https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L720

running in an anonymous thread will not catch AmazonClientException.

Off course, no matter how I call it, this will always crash.

```
    fun load()
    {
        // MQTT client IDs are required to be unique per AWS IoT account.
        clientId = MiscUtil.getAndroidId()

        topic = "xyz123"

        // Initialize the AWS Cognito credentials provider
        credentialsProvider = CognitoCachingCredentialsProvider(App.app, COGNITO_POOL_ID, IOT_REGION)

        // MQTT Client
        mqttManager = AWSIotMqttManager(clientId, IOT_ENDPOINT)
    }

```

Above method is called under a try/catch, not depicted above.

Can we fix this?

Full stack follow:
```
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.us-west-2.amazonaws.com": No address associated with hostname
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:389)
	at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:782)
	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:694)
	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
	at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$1.run(AWSIotMqttManager.java:720)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.net.UnknownHostException: Unable to resolve host "cognito-identity.us-west-2.amazonaws.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:95)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
	at java.net.InetAddress.getAllByName(InetAddress.java:757)
	at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
	at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:372)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:355)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:273)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:474)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
	at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
	at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
	... 10 more
java.net.UnknownHostException: Unable to resolve host "cognito-identity.us-west-2.amazonaws.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:95)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
	at java.net.InetAddress.getAllByName(InetAddress.java:757)
	at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
	at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:372)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:355)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:273)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:474)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
	at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
	at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:389)
	at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:782)
	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:694)
	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
	at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$1.run(AWSIotMqttManager.java:720)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by kvasukib** [comment]
@NightOwlCoder Sorry for the inconvenience caused. Can you check if the emulator when you were running your app/tests switched from one network to the other? I have encountered this issue when my emulator switches from one network to the other. If I restart the emulator and connect to the new network again, the app/tests work fine.

If I understand correctly, you are invoking `connect` method in the `AWSIotMqttManager`. The `connect` method accepts a callback and if there is an exception raised, the SDK invoke the callback. Have you passed in a valid callback? See https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L742

**Comment by NightOwlCoder** [comment]
Hey @kvasukib , yes I do have a callback which is never called.

The code you pointed to
`catch (final MqttException e) {`

catches `MqttException`, and what I'm seeing on the crash log is `AmazonClientException`, isn't that the reason?

**Comment by kvasukib** [comment]
Got it. AmazonClientException is a runtime exception. The SDK throws this exception when the SDK cannot handle an error scenario at runtime. You can catch this exception in your app and take corresponding action. Nonetheless, we will add more error handling mechanisms in the AWSIotMqttManager.

**Comment by NightOwlCoder** [comment]
I can't catch that, as it is under a thread you guys create.

**Comment by kvasukib** [comment]
@NightOwlCoder Apologies for the confusion. We will address this by catching the AmazonClientException and invoking the StatusCallback passed into the connect method.

**Comment by NightOwlCoder** [comment]
Hey there, any way for me getting an early release to test this?

My app keeps crashing, and I would like to help to get a faster fix.

**Comment by NightOwlCoder** [comment]
Hey @kvasukib, any feedback on this?

My app keeps crashing and I really need at least  a workaround...

Looks like every time there is a network hiccup it can't survive.

**Comment by kvasukib** [comment]
@NightOwlCoder Sorry for the delay. I have added exception handling and passing it back to the client status callback. This change will be released in the next revision of the SDK.

**Comment by kvasukib** [comment]
@NightOwlCoder This has been fixed in `2.7.7` version of the SDK. Please upgrade to the latest and let us know if you have any feedback. You can download the SDK from this page: https://aws.amazon.com/mobile/resources/. The maven artifact for `2.7.7` should be available soon.

**Comment by zhouxuemeng1988** [comment]
I have been having this problem for a year, thank you, and finally solved it.

**Comment by kvasukib** [comment]
Thank you @zhouxuemeng1988 for the feedback. Apologies for our delay in fixing it. Please let us know how your app testing goes and we welcome your feedback.

**Comment by zhouxuemeng1988** [comment]
@ kvasukib 
I am a developer in China. Our OTT customers are all over the world. When I find that the network speed is not good, or the network is abnormal, there will be frequent bugs.

`TIME=1514965079000
FINGERPRINT=HiSTBAndroidV5/Hi3798MV100/Hi3798MV100:4.4.2/Sbox8G40C/817120000073:eng/test-keys
HARDWARE=bigfish
UNKNOWN=unknown
RADIO=HiSTBAndroidV600R001C00SPC065
BOARD=bigfish
versionCode=79
PRODUCT=Hi3798MV100
versionName=3.1.7
DISPLAY=Sbox8G40C test-keys
USER=jenkins
HOST=Jenkins-Pub01
DEVICE=Hi3798MV100
TAGS=test-keys
MODEL=Sbox8G40C
BOOTLOADER=unknown
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=true
devicesId=ff7da49d64cbef7c
ID=Sbox8G40C
SERIAL=005501FF0001181001F808A5C869CBDA
MANUFACTURER=Hisilicon
BRAND=HiSTBAndroidV5
TYPE=eng
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.us-west-2.amazonaws.com": No address associated with hostname
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:448)
	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
	at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:678)
	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
	at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$1.run(AWSIotMqttManager.java:708)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.net.UnknownHostException: Unable to resolve host "cognito-identity.us-west-2.amazonaws.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:394)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
	at java.net.InetAddress.getAllByName(InetAddress.java:214)
	at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:216)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:122)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:292)
	at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
	at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
	at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
	... 11 more
java.net.UnknownHostException: Unable to resolve host "cognito-identity.us-west-2.amazonaws.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:394)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
	at java.net.InetAddress.getAllByName(InetAddress.java:214)
	at com.android.okhttp.internal.Dns$1.getAllByName(Dns.java:28)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:216)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:122)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:292)
	at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
	at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
	at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566)
	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:448)
	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
	at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:678)
	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
	at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$1.run(AWSIotMqttManager.java:708)
	at java.lang.Thread.run(Thread.java:841)
`

**Comment by kvasukib** [comment]
@zhouxuemeng1988 The issue you raised is different from the original issue. This happens when the network is not reachable. You can add a check for network reachability in your app before making a network call. Can you open a new issue for this and we can discuss there?

**Comment by zhouxuemeng1988** [comment]
> @zhouxuemeng1988 The issue you raised is different from the original issue. This happens when the network is not reachable. You can add a check for network reachability in your app before making a network call. Can you open a new issue for this and we can discuss there?

`com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.us-west-2.amazonaws.com": No address associated with hostname at `
This looks like the same bug

**Comment by tajchert** [comment]
I'm still having that issue on 2.7.7 SDK.

Crash log:
`com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.eu-central-1.amazonaws.com": No address associated with hostname
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:448)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:678)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:77)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:5200)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.scan(AmazonDynamoDBClient.java:2481)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper.scan(DynamoDBMapper.java:2264)
2018-11-12 20:58:20.798 6233-6281/pl.tajchert.canary W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper.scan(DynamoDBMapper.java:2228)`

**Comment by kvasukib** [comment]
@tajchert Please use #567 for your issue as it is different from #556.

**Comment by tajchert** [comment]
It doesn't look like #567 as it mentions Read timeout in exception, and mine as well this one ( #556 ) mentions: 
`AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.eu-central-1.amazonaws.com": No address associated with hostname` and have same stacktrace.
Which seems like correct fit, or maybe both of them have similar origin (?)

**Comment by NightOwlCoder** [comment]
@kvasukib hey there, is there a way for me to increase log level?

**Comment by GiovanniVisentini** [comment]
I have the same exception using the pinpoint service, I'm assuming that if the mobile is offline the event is cached, instead the app crash.
the stack trace is:

`Fatal Exception: java.lang.RuntimeException: Failed to get credentials from Cognito Identity
       at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:265)
       at com.amazonaws.services.pinpoint.AmazonPinpointClient.invoke(AmazonPinpointClient.java:3872)
       at com.amazonaws.services.pinpoint.AmazonPinpointClient.updateEndpoint(AmazonPinpointClient.java:3630)
       at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient$1.run(TargetingClient.java:198)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)`


`Caused by com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.us-east-1.amazonaws.com": No address associated with hostname
       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:389)
       at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:782)
       at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:694)
       at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
       at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:259)
       at com.amazonaws.services.pinpoint.AmazonPinpointClient.invoke(AmazonPinpointClient.java:3872)
       at com.amazonaws.services.pinpoint.AmazonPinpointClient.updateEndpoint(AmazonPinpointClient.java:3630)
       at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient$1.run(TargetingClient.java:198)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)`

`Caused by java.net.UnknownHostException: Unable to resolve host "cognito-identity.us-east-1.amazonaws.com": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:95)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
       at java.net.InetAddress.getAllByName(InetAddress.java:752)
       at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
       at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
       at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:345)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
       at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:162)
       at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:75)
       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:371)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:566)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:389)
       at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:782)
       at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:694)
       at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:465)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:485)
       at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:259)
       at com.amazonaws.services.pinpoint.AmazonPinpointClient.invoke(AmazonPinpointClient.java:3872)
       at com.amazonaws.services.pinpoint.AmazonPinpointClient.updateEndpoint(AmazonPinpointClient.java:3630)
       at com.amazonaws.mobileconnectors.pinpoint.targeting.TargetingClient$1.run(TargetingClient.java:198)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)`

I'm using SDK v 2.8.3

Thanks

**Comment by minbi** [comment]
Hi @GiovanniVisentini ,

Can you open a different issue? You do have a similar stacktrace, but since you are using Pinpoint the fix will be else where in the code. This thread is getting crowded by different code fixes.

Thanks

**Comment by GiovanniVisentini** [comment]
@minbi ok sorry, I open issue #588
