### ISSUE TITLE
Using TransferUtility in a background service in different process

### ISSUE THREAD

**Issue by zhoul-HS** [aws/aws-sdk-android#86]
Opening a new issue as requested in #85 

As said, I've managed to get the TransferService to open on the same process as my background service, by adding `android:process=":remote"` to the manifest declaration:
```xml
        <service
            android:name=".MyService"
            android:process=":remote"
            android:enabled="true"
            android:exported="false"/>

        <service
            android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService"
            android:process=":remote"
            android:enabled="true" />
```

Now for some reason, i'm getting this error:
`java.lang.RuntimeException: Handler (android.os.Handler) {53730afc} sending message to a Handler on a dead thread`

**Comment by zhoul-HS** [comment]
stack trace:
```
W/MessageQueue: Handler (android.os.Handler) {5384e598} sending message to a Handler on a dead thread
                                                                            java.lang.RuntimeException: Handler (android.os.Handler) {5384e598} sending message to a Handler on a dead thread
                                                                                at android.os.MessageQueue.enqueueMessage(MessageQueue.java:294)
                                                                                at android.os.Handler.sendMessageAtTime(Handler.java:473)
                                                                                at android.os.Handler.sendMessageDelayed(Handler.java:446)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.TransferService.enqueueCheckTasksDoneLater(TransferService.java:189)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.TransferService.access$200(TransferService.java:44)
                                                                                at com.amazonaws.mobileconnectors.s3.transferutility.TransferService$2.handleMessage(TransferService.java:166)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:137)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:60)
```

don't understand why...

**Comment by fosterzhang** [comment]
@zhoul-HS are there any warning messages before that?

**Comment by zhoul-HS** [comment]
That's exactly what was happening. I got an ANR which dropped my service.
It seems to be working now (turned on the developer option to show ANR dialog for background process).
Now I need to figure out what blocks my mainThread.

**Comment by zhoul-HS** [comment]
Well, it seems I have to keep a strong reference to the S3 client, since TransferUtility has a weak reference to it, and if I just run it in a simple private method, it gets garbage collected.

**Comment by pabliko93** [comment]
I also get an ANR message in some devices while running the S3 TransferUtility.
It seems like if the service takes big portion of the CPU...
If I run the app in a better device (Galaxy s5) it doesn't cause any problems even if the app is running for 12 hours...

**Comment by fosterzhang** [comment]
@zhoul-HS Yes, the S3 client needs a longer life cycle.
@pabliko93 We are aware of the performance issue, and we will address it ASAP.

Resolving this issue. Feel free to reopen it.
