### ISSUE TITLE
Unable to execute HTTP request: Unable to resolve host *** No address associated with hostname when use Kinesis SDK

### ISSUE THREAD

**Issue by sakebook** [aws/aws-sdk-android#98]
I use Kinesis SDK and Core SDK v 2.2.11 on Android.

When calling `KinesisRecorder#submitAllRecords()`, sometimes the following error will occur .

```
Fatal Exception: com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "cognito-identity.ap-northeast-1.amazonaws.com": No address associated with hostname
       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:421)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:533)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:406)
       at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:627)
       at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:553)
       at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:370)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:440)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:76)
       at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2516)
       at com.amazonaws.services.kinesis.AmazonKinesisClient.putRecords(AmazonKinesisClient.java:808)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.KinesisStreamRecordSender.sendBatch(KinesisStreamRecordSender.java:71)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.AbstractKinesisRecorder.submitAllRecords(AbstractKinesisRecorder.java:138)
       at jp.newsdigest.logic.AppLogManager.submitLogs(AppLogManager.java:54)
       at jp.newsdigest.services.LogSubmitService.onRunTask(LogSubmitService.java:41)
       at com.google.android.gms.gcm.GcmTaskService$zza.run(Unknown Source)
Caused by java.net.UnknownHostException: Unable to resolve host "cognito-identity.ap-northeast-1.amazonaws.com": No address associated with hostname
       at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:367)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:295)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:217)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
       at com.amazonaws.http.UrlHttpClient.writeContentToConnection(UrlHttpClient.java:128)
       at com.amazonaws.http.UrlHttpClient.execute(UrlHttpClient.java:65)
       at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:353)
       at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:196)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:533)
       at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getCredentialsForIdentity(AmazonCognitoIdentityClient.java:406)
       at com.amazonaws.auth.CognitoCredentialsProvider.populateCredentialsWithCognito(CognitoCredentialsProvider.java:627)
       at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:553)
       at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:370)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:440)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:76)
       at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2516)
       at com.amazonaws.services.kinesis.AmazonKinesisClient.putRecords(AmazonKinesisClient.java:808)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.KinesisStreamRecordSender.sendBatch(KinesisStreamRecordSender.java:71)
       at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.AbstractKinesisRecorder.submitAllRecords(AbstractKinesisRecorder.java:138)
```

I am writing in the following the following URL in the reference.
 > https://github.com/aws/aws-sdk-java/issues/321

Code of the submit portion wrote in the following.

```
        KinesisRecorderConfig config = new KinesisRecorderConfig();
        ClientConfiguration clientConfiguration = config.getClientConfiguration();
        clientConfiguration.setMaxErrorRetry(3);
        clientConfiguration.setConnectionTimeout(5 * 1000);
        clientConfiguration.setSocketTimeout(5 * 1000);

        File directory = context.getCacheDir();
        CognitoCachingCredentialsProvider provider =
                new CognitoCachingCredentialsProvider(
                        context,
                        BuildConfig.LOG_POOL_ID,
                        Regions.AP_NORTHEAST_1);
        KinesisRecorder recorder = new KinesisRecorder(directory, Regions.AP_NORTHEAST_1, provider, config);
        recorder.submitAllRecords();
```

and wrote Application class

```
java.security.Security.setProperty("networkaddress.cache.ttl", "60");
```

I'm in trouble. Please help.

**Comment by wdane** [comment]
Hi Sakebook,

Are you on a stable internet connection like strong Wi-Fi or testing with 4/3G? Are you able to contact any other http endpoints? Is this intermittent or permanently happening?

**Comment by sakebook** [comment]
Thank you for your reply!

 > Are you on a stable internet connection like strong Wi-Fi or testing with 4/3G?

I do not know because the crash report.
However, I think that's probably 4 / 3G.

 > Are you able to contact any other http endpoints?

Also in the crash report, I do not know not to reproduce at hand. 

> Is this intermittent or permanently happening?

According to the crash report, it has intermittently occur.

**Comment by fosterzhang** [comment]
@sakebook I think this is irrelevant to timeout. `UnknownHostException` usually implies no network connection. Two possible causes:
- make sure your app has permission `android.permission.INTERNET`.
- make sure the device has a network connection, either cellular data or Wifi.

FYI: Kinesis persists data on disk. No data is lost when there is no network. I suggest you put a try catch around `KinesisRecorder#submitAllRecords()` and submit it a later time.

**Comment by sakebook** [comment]
@fosterzhang 
I got it. It sounds like the network has occurred unstable.

Since the data is stored, I think that trying to avoid in the try-catch.
Thank you very much.

The following is a demand.
To avoid this crash, do you can not cope in the way of the SDK?
This workaround is, I think that non-essential.

**Comment by fosterzhang** [comment]
@sakebook Sorry I didn't get your question. Would you please rephrase it?

FYI, `KinesisRecorder#submitAllRecords()` may throw unchecked exception `AmazonClientException`. To avoid crashing the app, it'd better to put a try catch block around it.

**Comment by sakebook** [comment]
@fosterzhang 

I'm sorry, my English is not good.

As you say, it can be avoided by try-catch.

However, if what this exception is assumed already, is not it should be implemented as follows: in the SDK side? Like a JSONObject.

```
public synchronized void submitAllRecords () throws AmazonClientException {
     ...
}
```

If not already assumed, I think it is better that the refurbishment in the SDK side.

**Comment by fosterzhang** [comment]
Sorry for the late reply. For legacy reason AmazonClientException is a runtime exception. Declaring an unchecked exception in the method signature is optional. I am leaning toward not declaring it per Java's best practice. However I do agree with you it should be documented.

Resolving this as it's not an SDK issue. Please feel free to reopen it.

**Comment by sakebook** [comment]
Thank you for the reply.
I fully understand.

I closes this Issue.
